"""
Tests: PR-A (fix/db-down-all-instances) — partgraph.util.lifecycle (leaf module).

Specifies the behaviour of the NEW leaf module ``partgraph.util.lifecycle``,
which gives `partgraph db down` a SECOND lifecycle-owner sweep (a quadlet/
systemd unit generated by compose2quadlet.sh from the SAME docker-compose.yml,
declaring the same ``ContainerName=partgraph-dgraph``) on top of the existing
Compose-only stop, so a single `db down` leaves ZERO PartGraph instances
running for 0/1/N instances, however they were started — while PROVABLY never
touching an unrelated cve-graph stack running on the same host.

Pinned contract (leaf module ``partgraph.util.lifecycle`` — NOT YET
IMPLEMENTED; collection of THIS file is expected to ERROR with
ModuleNotFoundError until it exists, and that is the correct test-first red
state — mirrors tests/unit/test_health.py's original design before
partgraph.util.health existed):

Imports: stdlib only, plus ``partgraph.util.container``
(``engine_command``/``compose_command``) and ``partgraph.util.health``
(``probe_health``). NEVER imports ``partgraph.cli`` or any embed/query/load
module (leaf discipline; mirrors container.py / health.py / index_health.py).
NOT re-exported from ``partgraph/util/__init__.py`` (ADR-0018 Section 4
precedent, set by index_health.py).

Module constants (frozen, named — never derived at runtime):
  - ``PARTGRAPH_CONTAINER_NAME: str`` = "partgraph-dgraph" — the S1 selector:
    the EXACT container name docker/docker-compose.yml declares.
  - ``PARTGRAPH_DATA_VOLUME: str`` = "partgraph_dgraph_data" — the S2
    selector: the named data volume declared in docker-compose.yml.
  - ``PARTGRAPH_UNIT_NAME: str`` = "partgraph-dgraph.service" — the quadlet
    unit name. A FROZEN CONSTANT: never built from any engine-returned string
    (Sec finding — a poisoned container name must never be able to influence
    which systemd unit gets targeted).
  - ``PARTGRAPH_WATCHED_PORTS: tuple[int, ...]`` = (8081, 9081, 8001) — the S3
    selector: PartGraph's own reserved host ports (docker/docker-compose.yml).
  - ``ENUMERATE_TIMEOUT_S``, ``INSPECT_TIMEOUT_S``, ``STOP_TIMEOUT_S``,
    ``SYSTEMCTL_TIMEOUT_S``: finite, named, bounded ``float`` timeouts for
    every subprocess.run call this module makes (mirrors
    HEALTH_PROBE_TIMEOUT_S / ADR-0007's bounded-constant precedent). NEVER
    ``None`` (unbounded).
  - ``STOP_GRACE_SECONDS: int`` — the engine's OWN ``-t`` grace-period value
    passed to ``stop -t <n> <name>`` (distinct from the Python-level
    subprocess ``timeout=`` kwarg above).

Frozen dataclasses:
  - ``Instance(name: str, image: str, status: str, ports: tuple[int, ...],
    owned_by: str, mounts_data_volume: bool)`` — ``owned_by`` is one of the
    literal strings ``"S1"``/``"S2"``/``"S3"``. Only S1/S2/S3-classified
    containers are ever returned by :func:`find_partgraph_instances` — an
    unrelated container (e.g. every cve-graph container) is excluded
    entirely, never present in the returned tuple with some other tag.
  - ``UnitState(present: bool, load_state: str | None,
    active_state: str | None, wanted_by_default: bool | None)`` —
    ``wanted_by_default`` is ``None`` when undeterminable (NEVER guessed).
  - ``DownResult(stopped: tuple[str, ...],
    skipped_foreign_port_holders: tuple[str, ...], unit_stopped: bool,
    survivors: tuple[str, ...], still_serving_health: bool)``.

Public functions (the ONLY public surface; everything else is private):
  - ``find_partgraph_instances(*, engine_prefix: list[str] | None = None,
    which=shutil.which, environ=None) -> tuple[Instance, ...]`` — READ-ONLY.
    Runs ``<prefix> ps --all --format json`` (never ``--filter``), then, for
    EVERY returned container, ``<prefix> container inspect --format json
    <container-id>`` (by opaque ID — NEVER by name, so a foreign container's
    NAME never reaches an inspect argv) to determine
    :attr:`Instance.mounts_data_volume`. Classifies ownership by exact Python
    string comparison (S1: name == PARTGRAPH_CONTAINER_NAME; S2: mounts
    PARTGRAPH_DATA_VOLUME; S3: holds a PARTGRAPH_WATCHED_PORTS host port and
    matches neither S1 nor S2). A name failing a strict, hostile-input
    charset check is EXCLUDED before classification — it is never returned,
    and its raw string never reaches any subprocess argv. ``engine_prefix``
    defaults to :func:`partgraph.util.container.engine_command`'s result when
    ``None`` (resolved with the given ``which``/``environ``).
  - ``unit_state(*, which=shutil.which) -> UnitState`` — READ-ONLY. Runs
    ``systemctl --user show <PARTGRAPH_UNIT_NAME> --property=LoadState
    --property=ActiveState --property=SubState --property=UnitFileState
    --property=WantedBy`` and parses the ``Key=Value`` lines. Returns
    ``UnitState(present=False, ...)`` WITHOUT invoking subprocess at all when
    ``which("systemctl")`` is ``None``.
  - ``stop_all(*, engine_prefix=None, which=shutil.which, environ=None,
    compose_down: Callable[[], None] | None = None,
    probe_health: Callable[[], Any] | None = None,
    dry_run: bool = False) -> DownResult`` — the full orchestrator. Order:
    (1) query :func:`unit_state`; if present and active, run ``systemctl
    --user stop <PARTGRAPH_UNIT_NAME>`` (skipped entirely under
    ``dry_run=True``); (2) call the injected ``compose_down`` callback
    (skipped under ``dry_run=True``; never called with ``None`` under a real
    run); (3) call :func:`find_partgraph_instances` and, for every SURVIVING
    S1/S2 instance, run ``<prefix> stop -t <STOP_GRACE_SECONDS> <name>``
    (skipped under ``dry_run=True`` — enumeration/inspection still happens,
    nothing is stopped); (4) call :func:`find_partgraph_instances` AGAIN
    (verification re-enumeration) to populate ``survivors``. ``probe_health``
    defaults to a lazy import of :func:`partgraph.util.health.probe_health`
    when ``None``; the injected seam is how `partgraph.cli`'s ALREADY
    module-level-imported ``probe_health`` (patched by CLI tests at
    ``partgraph.cli.probe_health``) flows through to this leaf without the
    leaf importing anything from ``partgraph.cli``.

This file mirrors the hermetic, injected-seam style of test_container.py
(fake ``which``) and test_health.py (fake HTTP seam / dataclass-contract
checks): no test in this file opens a real socket, starts a real container,
sleeps, or reads the real wall clock. Every subprocess outcome is injected via
a scripted fake ``subprocess.run`` (patched at the ``subprocess.run`` call
site, mirroring how cli.py's own ``_run_compose`` is tested).
"""

from __future__ import annotations

import dataclasses
import inspect
import json
import math
import re
import subprocess
from types import SimpleNamespace
from unittest.mock import patch

import pytest

# ---------------------------------------------------------------------------
# Lazy/eager import guard: this whole file is expected to ERROR at collection
# with ModuleNotFoundError until src/partgraph/util/lifecycle.py exists — the
# correct test-first red state (mirrors test_health.py before health.py
# existed).
# ---------------------------------------------------------------------------

from partgraph.util.lifecycle import (  # noqa: E402
    ENUMERATE_TIMEOUT_S,
    INSPECT_TIMEOUT_S,
    PARTGRAPH_CONTAINER_NAME,
    PARTGRAPH_DATA_VOLUME,
    PARTGRAPH_UNIT_NAME,
    PARTGRAPH_WATCHED_PORTS,
    STOP_GRACE_SECONDS,
    STOP_TIMEOUT_S,
    SYSTEMCTL_TIMEOUT_S,
    DownResult,
    Instance,
    UnitState,
    find_partgraph_instances,
    stop_all,
    unit_state,
)

# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------


def _ps_row(container_id: str, name: str, image: str, *, state: str = "running",
            host_ports: tuple[int, ...] = ()) -> dict:
    """Build one canonical `<engine> ps --all --format json` row.

    A single, consistent per-row schema is used for BOTH the JSON-array and
    the NDJSON fixtures in this file: the LIVE-VERIFIED unknown is the OUTER
    envelope shape (array vs newline-delimited), not the per-row field names.
    """
    return {
        "Id": container_id,
        "Names": [name],
        "Image": image,
        "State": state,
        "Ports": [
            {
                "host_ip": "127.0.0.1",
                "host_port": p,
                "container_port": 8080,
                "protocol": "tcp",
            }
            for p in host_ports
        ],
    }


def _mounts(*volume_names: str, destination: str = "/dgraph") -> list[dict]:
    """Build a `container inspect --format json` `.Mounts` fixture."""
    return [
        {"Type": "volume", "Name": v, "Destination": destination}
        for v in volume_names
    ]


class _Proc:
    """Minimal stand-in for subprocess.CompletedProcess."""

    def __init__(self, *, stdout: str = "", stderr: str = "", returncode: int = 0) -> None:
        self.stdout = stdout
        self.stderr = stderr
        self.returncode = returncode


def _is_ps_call(argv: list[str]) -> bool:
    return "ps" in argv and "--all" in argv


def _is_inspect_call(argv: list[str]) -> bool:
    return "container" in argv and "inspect" in argv


def _is_engine_stop_call(argv: list[str]) -> bool:
    return argv and argv[0] != "systemctl" and "stop" in argv and "compose" not in argv


def _is_systemctl_show_call(argv: list[str]) -> bool:
    return bool(argv) and argv[0] == "systemctl" and "show" in argv


def _is_systemctl_stop_call(argv: list[str]) -> bool:
    return bool(argv) and argv[0] == "systemctl" and "stop" in argv and "show" not in argv


def _make_scripted_run(
    *,
    ps_rows: list[dict],
    mounts_by_id: dict[str, list[dict]] | None = None,
    unit_lines: list[str] | None = None,
    ps_stdout_override: str | None = None,
):
    """Return (fake_run, calls) — a subprocess.run stand-in and its call log.

    ``fake_run`` dispatches on argv shape (never trusts call ORDER) so a test
    can describe WHAT is running rather than HOW the module discovers it.
    ``ps_stdout_override`` lets a test replace the ps response body verbatim
    (empty string / malformed text) while still routing through the same
    dispatcher for inspect/systemctl calls.
    """
    mounts_by_id = mounts_by_id or {}
    unit_lines = unit_lines if unit_lines is not None else [
        "LoadState=not-found",
        "ActiveState=",
        "SubState=",
        "UnitFileState=",
        "WantedBy=",
    ]
    calls: list[tuple[list[str], dict]] = []

    def _fake(argv, **kwargs):
        calls.append((list(argv), dict(kwargs)))
        if _is_systemctl_show_call(argv):
            return _Proc(stdout="\n".join(unit_lines))
        if _is_systemctl_stop_call(argv):
            return _Proc(returncode=0)
        if _is_inspect_call(argv):
            cid = argv[-1]
            return _Proc(stdout=json.dumps([{"Id": cid, "Mounts": mounts_by_id.get(cid, [])}]))
        if _is_ps_call(argv):
            if ps_stdout_override is not None:
                return _Proc(stdout=ps_stdout_override)
            return _Proc(stdout=json.dumps(ps_rows))
        if _is_engine_stop_call(argv):
            return _Proc(returncode=0)
        raise AssertionError(f"unscripted subprocess.run call in test fixture: {argv}")

    return _fake, calls


# ---------------------------------------------------------------------------
# CONTRACT — module constants
# ---------------------------------------------------------------------------


def test_partgraph_container_name_and_volume_constants_match_compose_file() -> None:
    """Given the compose file declares container_name and volume literals.
    When the module constants are read directly.
    Then they equal the exact values docker/docker-compose.yml declares.
    """
    assert PARTGRAPH_CONTAINER_NAME == "partgraph-dgraph"
    assert PARTGRAPH_DATA_VOLUME == "partgraph_dgraph_data"
    assert set(PARTGRAPH_WATCHED_PORTS) == {8081, 9081, 8001}


@pytest.mark.parametrize(
    "constant",
    [ENUMERATE_TIMEOUT_S, INSPECT_TIMEOUT_S, STOP_TIMEOUT_S, SYSTEMCTL_TIMEOUT_S],
)
def test_named_timeouts_are_finite_bounded_floats(constant: float) -> None:
    """Given every subprocess call this module makes carries a bounded timeout.
    When each named timeout constant is read directly.
    Then it is a finite float strictly greater than zero (never None/unbounded
    — mirrors HEALTH_PROBE_TIMEOUT_S / ADR-0007's bounded-constant precedent).
    """
    assert isinstance(constant, float)
    assert math.isfinite(constant)
    assert constant > 0


def test_stop_grace_seconds_is_a_positive_bounded_int() -> None:
    """Given STOP_GRACE_SECONDS is the engine's OWN `-t` grace period.
    When it is read directly.
    Then it is a positive int, distinct from the Python-level STOP_TIMEOUT_S
    subprocess watchdog (the watchdog must exceed the grace period, or the
    Python side would abort before the engine's own grace period elapses).
    """
    assert isinstance(STOP_GRACE_SECONDS, int)
    assert STOP_GRACE_SECONDS > 0
    assert STOP_TIMEOUT_S > STOP_GRACE_SECONDS


# ---------------------------------------------------------------------------
# CONTRACT — dataclass shapes
# ---------------------------------------------------------------------------


def test_dataclasses_are_frozen_with_exact_contract_fields() -> None:
    """CONTRACT: Given Instance/UnitState/DownResult are the DTOs this module
    returns.
    When each is instantiated.
    Then each exposes EXACTLY its pinned field set and is frozen (a consumer
    cannot mutate a result after the fact — mirrors HealthResult).
    """
    instance = Instance(
        name="partgraph-dgraph", image="dgraph/standalone:v25.3.4",
        status="running", ports=(8081,), owned_by="S1", mounts_data_volume=True,
    )
    assert {f.name for f in dataclasses.fields(instance)} == {
        "name", "image", "status", "ports", "owned_by", "mounts_data_volume",
    }
    with pytest.raises(dataclasses.FrozenInstanceError):
        instance.owned_by = "S2"  # type: ignore[misc]

    unit = UnitState(present=True, load_state="loaded", active_state="active",
                      wanted_by_default=True)
    assert {f.name for f in dataclasses.fields(unit)} == {
        "present", "load_state", "active_state", "wanted_by_default",
    }
    with pytest.raises(dataclasses.FrozenInstanceError):
        unit.present = False  # type: ignore[misc]

    result = DownResult(
        stopped=(), skipped_foreign_port_holders=(), unit_stopped=False,
        survivors=(), still_serving_health=False,
    )
    assert {f.name for f in dataclasses.fields(result)} == {
        "stopped", "skipped_foreign_port_holders", "unit_stopped",
        "survivors", "still_serving_health",
    }
    with pytest.raises(dataclasses.FrozenInstanceError):
        result.unit_stopped = True  # type: ignore[misc]


def test_unit_state_wanted_by_default_is_none_when_undeterminable() -> None:
    """CONTRACT: Given UnitState.wanted_by_default per contract must be
    ``None`` when undeterminable rather than guessed.
    When a UnitState is built with no WantedBy evidence.
    Then wanted_by_default is None (not True and not False).
    """
    unit = UnitState(present=False, load_state=None, active_state=None,
                      wanted_by_default=None)
    assert unit.wanted_by_default is None


# ---------------------------------------------------------------------------
# AC-P2 — ps output parsing: JSON array vs NDJSON must be identical
# ---------------------------------------------------------------------------


def test_parse_ps_json_array() -> None:
    """AC-P2: Given `<engine> ps --all --format json` answers with a single
    JSON ARRAY (podman's documented outer shape).
    When find_partgraph_instances() is called.
    Then the exact-name match is parsed into an S1 Instance with the right
    name/image/status/ports.
    """
    rows = [_ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4",
                     host_ports=(8081, 9081, 8001))]
    fake_run, _calls = _make_scripted_run(
        ps_rows=rows, mounts_by_id={"id-s1": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    inst = instances[0]
    assert inst.name == "partgraph-dgraph"
    assert inst.image == "dgraph/standalone:v25.3.4"
    assert inst.status == "running"
    assert set(inst.ports) == {8081, 9081, 8001}
    assert inst.owned_by == "S1"


def test_parse_ps_ndjson() -> None:
    """AC-P2: Given the SAME single-container fixture as the JSON-array test,
    but `ps` answers with newline-delimited JSON (docker's outer shape)
    instead of a JSON array.
    When find_partgraph_instances() is called.
    Then the result is IDENTICAL to the JSON-array case — the parser accepts
    BOTH outer shapes and produces the same Instance.
    """
    row = _ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4",
                   host_ports=(8081, 9081, 8001))
    ndjson = json.dumps(row) + "\n"
    fake_run, _calls = _make_scripted_run(
        ps_rows=[row], mounts_by_id={"id-s1": _mounts("partgraph_dgraph_data")},
        ps_stdout_override=ndjson,
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].name == "partgraph-dgraph"
    assert instances[0].owned_by == "S1"


def test_parse_ps_empty_returns_empty() -> None:
    """AC-P2: Given `ps --all --format json` answers with an EMPTY string
    (zero containers on the host at all).
    When find_partgraph_instances() is called.
    Then it returns an empty tuple — never raises.
    """
    fake_run, _calls = _make_scripted_run(ps_rows=[], ps_stdout_override="")
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert instances == ()


def test_parse_ps_malformed_returns_empty() -> None:
    """AC-P2: Given `ps --all --format json` answers with garbage/non-JSON
    text (a corrupt engine response).
    When find_partgraph_instances() is called.
    Then it returns an empty tuple — never raises, never crashes `db down`.
    """
    fake_run, _calls = _make_scripted_run(
        ps_rows=[], ps_stdout_override="{not json at all]###"
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert instances == ()


# ---------------------------------------------------------------------------
# Selector policy (S1 / S2 / S3) — locked
# ---------------------------------------------------------------------------


def test_selects_exact_name_only() -> None:
    """Given one container named EXACTLY 'partgraph-dgraph' and a SECOND
    container named 'partgraph-dgraph-backup' (a substring/prefix collision,
    mounting nothing, holding no watched port).
    When find_partgraph_instances() is called.
    Then only the EXACT match is classified S1; the '-backup' container is
    excluded entirely — S1 is exact string equality, never a prefix/substring
    match.
    """
    rows = [
        _ps_row("id-exact", "partgraph-dgraph", "dgraph/standalone:v25.3.4"),
        _ps_row("id-backup", "partgraph-dgraph-backup", "dgraph/standalone:v25.3.4"),
    ]
    fake_run, _calls = _make_scripted_run(
        ps_rows=rows,
        mounts_by_id={"id-exact": [], "id-backup": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name: i.owned_by for i in instances}
    assert names.get("partgraph-dgraph") == "S1"
    assert "partgraph-dgraph-backup" not in names, (
        "A substring/prefix name match must NEVER be classified S1: "
        f"got instances={instances!r}"
    )


def test_selects_by_data_volume_mount() -> None:
    """Given a container with an ARBITRARY name (e.g. the quadlet-generated
    duplicate) that mounts the named `partgraph_dgraph_data` volume at
    /dgraph, and does NOT hold any watched port.
    When find_partgraph_instances() is called.
    Then it is classified S2 with mounts_data_volume=True — ownership is
    volume-mount based, independent of name.
    """
    rows = [_ps_row("id-quadlet", "systemd-partgraph-dgraph", "dgraph/standalone:v25.3.4")]
    fake_run, _calls = _make_scripted_run(
        ps_rows=rows,
        mounts_by_id={"id-quadlet": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].owned_by == "S2"
    assert instances[0].mounts_data_volume is True


def test_port_holder_is_report_only() -> None:
    """Given a container with an ARBITRARY name, no PartGraph volume mount,
    holding host port 8081 (one of PARTGRAPH_WATCHED_PORTS).
    When find_partgraph_instances() is called AND stop_all() runs end-to-end
    on this fixture (nothing else present).
    Then the enumeration classifies it S3, AND stop_all() records it under
    ``skipped_foreign_port_holders`` — it is NEVER passed to an engine `stop`
    call (report-only, never stopped).
    """
    rows = [_ps_row("id-foreign", "some-other-service", "nginx:1.27.3",
                     host_ports=(8081,))]
    fake_run, calls = _make_scripted_run(
        ps_rows=rows, mounts_by_id={"id-foreign": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
        assert instances[0].owned_by == "S3"

        result = stop_all(
            engine_prefix=["docker"],
            compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    assert "some-other-service" in result.skipped_foreign_port_holders
    assert result.stopped == ()
    for argv, _kwargs in calls:
        assert not _is_engine_stop_call(argv), (
            f"An S3 (report-only) port holder must NEVER be `stop`-ped: {argv}"
        )


def test_cve_graph_fixture_selects_nothing() -> None:
    """A6 (HIGHEST PRIORITY NEGATIVE): Given the REAL observed host state
    (names/images only — live-verified this session) — zero PartGraph
    containers and exactly these five dgraph-family/unrelated containers, on
    host ports distinct from PARTGRAPH_WATCHED_PORTS (illustrative test
    values; the live session did not record their exact port numbers):
    min-web (nginx:1.27.3), cve-ratel (dgraph/ratel:latest),
    cve-zero (dgraph/dgraph:v24.0.0), cve-alpha (dgraph/dgraph:v24.0.0),
    cve-loader (localhost/cve-loader:latest).
    When find_partgraph_instances() is called.
    Then it returns an EMPTY tuple — none of the five match S1 (name), S2
    (volume) or S3 (watched port); image family (`dgraph/*`) is NOT a
    selector.
    """
    rows = [
        _ps_row("cid-minweb", "min-web", "nginx:1.27.3", host_ports=(18080,)),
        _ps_row("cid-ratel", "cve-ratel", "dgraph/ratel:latest", host_ports=(18000,)),
        _ps_row("cid-zero", "cve-zero", "dgraph/dgraph:v24.0.0", host_ports=(15080,)),
        _ps_row("cid-alpha", "cve-alpha", "dgraph/dgraph:v24.0.0", host_ports=(18081, 19081)),
        _ps_row("cid-loader", "cve-loader", "localhost/cve-loader:latest"),
    ]
    mounts_by_id = {
        "cid-minweb": [],
        "cid-ratel": [],
        "cid-zero": _mounts("cve-graph_dgraph_zero", destination="/dgraph"),
        "cid-alpha": _mounts("cve-graph_dgraph_alpha", destination="/dgraph"),
        "cid-loader": [],
    }
    fake_run, calls = _make_scripted_run(ps_rows=rows, mounts_by_id=mounts_by_id)

    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert instances == (), (
        f"cve-graph fixture must select NOTHING; got: {instances!r}"
    )
    forbidden_names = {"min-web", "cve-ratel", "cve-zero", "cve-alpha", "cve-loader"}
    forbidden_volumes = {"cve-graph_dgraph_zero", "cve-graph_dgraph_alpha"}
    for argv, _kwargs in calls:
        argv_text = " ".join(argv)
        for forbidden in forbidden_names | forbidden_volumes | {"systemd-cve-graph"}:
            assert forbidden not in argv_text, (
                f"cve-graph identifier {forbidden!r} leaked into engine argv: {argv}"
            )
        assert not _is_engine_stop_call(argv)


def test_hostile_name_rejected() -> None:
    """A14: Given `ps` returns a container whose name starts with '-' (a
    flag-injection attempt) and ALSO mounts partgraph_dgraph_data (it would
    otherwise be a legitimate S2 match).
    When find_partgraph_instances() is called.
    Then the hostile-named row is EXCLUDED entirely (never returned as an
    Instance) and its raw string never reaches any subprocess argv anywhere.
    """
    hostile = "-rf ; rm -rf / #"
    rows = [_ps_row("id-hostile", hostile, "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        ps_rows=rows, mounts_by_id={"id-hostile": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert instances == (), (
        f"A hostile container name must never be classified/returned: {instances!r}"
    )
    for argv, _kwargs in calls:
        for token in argv:
            assert hostile not in token, (
                f"Hostile name leaked into subprocess argv: {argv}"
            )


@pytest.mark.parametrize(
    "hostile_name",
    ["-flag-like", "has space", "semi;colon", "dollar$sign", "quote'mark"],
)
def test_hostile_name_rejected_parametrized_charsets(hostile_name: str) -> None:
    """A14: Given a variety of hostile name shapes (leading '-', whitespace,
    ';', '$', quote).
    When find_partgraph_instances() is called on a fixture where that name
    mounts the data volume.
    Then every one is excluded and never reaches a subprocess argv.
    """
    rows = [_ps_row("id-x", hostile_name, "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        ps_rows=rows, mounts_by_id={"id-x": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert instances == ()
    for argv, _kwargs in calls:
        for token in argv:
            assert hostile_name not in token


# ---------------------------------------------------------------------------
# AC-P3 — engine-neutral argv (no --filter/--ignore authority, no Go-template
# field names, only verbs/flags documented for BOTH engines)
# ---------------------------------------------------------------------------


def test_no_docker_only_or_podman_only_flags() -> None:
    """AC-P3: Given a fixture requiring a ps call + at least one inspect call.
    When find_partgraph_instances() runs.
    Then NO argv anywhere uses `--filter` or `--ignore` as ownership
    authority, and no argv references a Go-template field (`{{.` anywhere).
    """
    rows = [_ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        ps_rows=rows, mounts_by_id={"id-s1": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        find_partgraph_instances(engine_prefix=["docker"])

    assert calls, "fixture produced no subprocess.run calls to inspect"
    for argv, _kwargs in calls:
        for token in argv:
            assert token != "--filter", f"--filter used as authority: {argv}"
            assert token != "--ignore", f"--ignore used: {argv}"
            assert "{{." not in token, f"Go-template field name relied upon: {argv}"


def test_engine_prefix_comes_from_engine_command() -> None:
    """AC-P1: Given engine_prefix is NOT explicitly supplied.
    When find_partgraph_instances() is called.
    Then it resolves the argv prefix via
    partgraph.util.container.engine_command() (patched here as a spy) —
    never a hard-coded 'docker'/'podman' literal.
    """
    fake_run, calls = _make_scripted_run(ps_rows=[], ps_stdout_override="[]")
    with (
        patch("partgraph.util.lifecycle.engine_command", return_value=["podman"]) as mock_engine,
        patch("subprocess.run", side_effect=fake_run),
    ):
        find_partgraph_instances()

    assert mock_engine.called, (
        "find_partgraph_instances() must resolve its engine prefix via "
        "engine_command() when engine_prefix is not supplied."
    )
    assert calls, "no subprocess.run call was made"
    assert calls[0][0][0] == "podman", (
        f"argv prefix must be engine_command()'s return value; got {calls[0][0]!r}"
    )


def test_all_calls_have_bounded_timeout() -> None:
    """A15: Given a fixture that triggers a ps call AND an inspect call.
    When find_partgraph_instances() runs.
    Then EVERY subprocess.run call carries a finite, positive `timeout=`
    kwarg — never an unbounded/absent timeout (a hung engine must never hang
    `db down`).
    """
    rows = [_ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        ps_rows=rows, mounts_by_id={"id-s1": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        find_partgraph_instances(engine_prefix=["docker"])

    assert calls
    for argv, kwargs in calls:
        timeout = kwargs.get("timeout")
        assert timeout is not None, f"call missing timeout=: {argv}"
        assert isinstance(timeout, int | float)
        assert math.isfinite(timeout)
        assert timeout > 0


# ---------------------------------------------------------------------------
# unit_state() — systemd quadlet unit introspection
# ---------------------------------------------------------------------------


def test_unit_state_parses_loaded_active() -> None:
    """A3: Given `systemctl --user show ...` answers with the LIVE-VERIFIED
    shape for a loaded, active unit wanted by default.target.
    When unit_state() is called.
    Then UnitState.present is True, load_state='loaded',
    active_state='active', wanted_by_default is True.
    """
    fake_run, calls = _make_scripted_run(
        ps_rows=[],
        unit_lines=[
            "LoadState=loaded",
            "ActiveState=active",
            "SubState=running",
            "UnitFileState=generated",
            "WantedBy=default.target",
        ],
    )
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        result = unit_state()

    assert result.present is True
    assert result.load_state == "loaded"
    assert result.active_state == "active"
    assert result.wanted_by_default is True
    assert len(calls) == 1
    assert _is_systemctl_show_call(calls[0][0])


def test_unit_state_parses_not_found() -> None:
    """A11: Given `systemctl --user show ...` answers LoadState=not-found (no
    such unit was ever generated on this host).
    When unit_state() is called.
    Then UnitState.present is False.
    """
    fake_run, _calls = _make_scripted_run(
        ps_rows=[],
        unit_lines=["LoadState=not-found", "ActiveState=inactive",
                    "SubState=dead", "UnitFileState=", "WantedBy="],
    )
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        result = unit_state()

    assert result.present is False


def test_unit_state_parses_failed() -> None:
    """Given `systemctl --user show ...` reports a loaded unit whose
    ActiveState is 'failed' (a crashed prior run).
    When unit_state() is called.
    Then UnitState.present is True and active_state == 'failed' — a failed
    unit is still 'present', distinct from not-found.
    """
    fake_run, _calls = _make_scripted_run(
        ps_rows=[],
        unit_lines=["LoadState=loaded", "ActiveState=failed",
                    "SubState=failed", "UnitFileState=generated",
                    "WantedBy=default.target"],
    )
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        result = unit_state()

    assert result.present is True
    assert result.active_state == "failed"


def test_unit_name_is_frozen_constant() -> None:
    """A3: Given PARTGRAPH_UNIT_NAME is a frozen module constant.
    When unit_state() builds its systemctl argv.
    Then the constant equals 'partgraph-dgraph.service' exactly, AND the
    argv passed to systemctl contains that exact constant string — never a
    name derived from ps/engine output.
    """
    assert PARTGRAPH_UNIT_NAME == "partgraph-dgraph.service"

    fake_run, calls = _make_scripted_run(ps_rows=[])
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        unit_state()

    assert calls
    assert PARTGRAPH_UNIT_NAME in calls[0][0]


def test_systemctl_argv_has_user_never_system_never_sudo() -> None:
    """A3: Given BOTH unit_state()'s read (show) call and stop_all()'s write
    (stop) call.
    When each systemctl invocation is inspected.
    Then every one contains '--user' and NEITHER 'sudo' as argv[0] NOR
    '--system' anywhere.
    """
    fake_run, calls = _make_scripted_run(
        ps_rows=[],
        unit_lines=["LoadState=loaded", "ActiveState=active",
                    "SubState=running", "UnitFileState=generated",
                    "WantedBy=default.target"],
    )
    with (
        patch("subprocess.run", side_effect=fake_run),
        patch("shutil.which", return_value="/usr/bin/systemctl"),
    ):
        unit_state()
        stop_all(
            engine_prefix=["docker"],
            compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    systemctl_calls = [argv for argv, _kwargs in calls if argv and argv[0] == "systemctl"]
    assert systemctl_calls, "no systemctl call was recorded"
    for argv in systemctl_calls:
        assert argv[0] != "sudo"
        assert "sudo" not in argv
        assert "--user" in argv
        assert "--system" not in argv


# ---------------------------------------------------------------------------
# AC-P4 — PARTGRAPH_CONTAINER_ENGINE routes through detection identically
# ---------------------------------------------------------------------------


def test_partgraph_container_engine_env_var_routes_through_detection() -> None:
    """AC-P4: Given PARTGRAPH_CONTAINER_ENGINE=docker is set in the injected
    environ mapping.
    When find_partgraph_instances() resolves its own engine prefix (no
    explicit engine_prefix override).
    Then engine_command() is called with that SAME environ — the override
    routes through the shared detection helper identically to how
    compose_command()/`db up`/`db down` already honour it.
    """
    fake_run, _calls = _make_scripted_run(ps_rows=[], ps_stdout_override="[]")
    with (
        patch(
            "partgraph.util.lifecycle.engine_command", return_value=["docker"]
        ) as mock_engine,
        patch("subprocess.run", side_effect=fake_run),
    ):
        find_partgraph_instances(environ={"PARTGRAPH_CONTAINER_ENGINE": "docker"})

    assert mock_engine.called
    _args, kwargs = mock_engine.call_args
    assert kwargs.get("environ") == {"PARTGRAPH_CONTAINER_ENGINE": "docker"}


# ---------------------------------------------------------------------------
# AC-P1 — no hard-coded engine literal in the leaf's own source
# ---------------------------------------------------------------------------


def test_ac_p1_lifecycle_source_never_hardcodes_docker_or_podman_argv_literal() -> None:
    """AC-P1: Given every engine invocation must begin with compose_command()
    or engine_command() output — never a literal.
    When src/partgraph/util/lifecycle.py's source text is scanned.
    Then it contains no argv-shaped list literal opening with "docker" or
    "podman" (e.g. `["docker"` / `['podman'`), which would bypass detection.

    Skips (does not fail red) if the source file does not exist yet — that is
    covered by this file's own module-level ModuleNotFoundError collection
    error, not by this specific static-scan assertion.
    """
    import pathlib

    module_path = (
        pathlib.Path(__file__).resolve().parent.parent.parent
        / "src" / "partgraph" / "util" / "lifecycle.py"
    )
    if not module_path.exists():
        pytest.skip("src/partgraph/util/lifecycle.py does not exist yet (expected pre-PR-A).")

    text = module_path.read_text(encoding="utf-8")
    forbidden = re.compile(r"""\[\s*["'](docker|podman)["']""")
    match = forbidden.search(text)
    assert match is None, (
        f"lifecycle.py hard-codes an engine literal in argv position: {match.group(0)!r}. "
        "Every engine invocation must begin with compose_command()/engine_command()."
    )
