"""
Tests: PR-A (fix/db-down-all-instances) — partgraph.util.lifecycle (leaf module).

Specifies the behaviour of the NEW leaf module ``partgraph.util.lifecycle``,
which gives `partgraph db down` a SECOND lifecycle-owner sweep (a quadlet/
systemd unit generated by compose2quadlet.sh from the SAME docker-compose.yml,
declaring the same ``ContainerName=partgraph-dgraph``) on top of the existing
Compose-only stop, so a single `db down` leaves ZERO PartGraph instances
running for 0/1/N instances, however they were started — while PROVABLY never
touching an unrelated cve-graph stack running on the same host.

Pinned contract (leaf module ``partgraph.util.lifecycle`` — NOT YET
IMPLEMENTED; collection of THIS file is expected to ERROR with
ModuleNotFoundError until it exists, and that is the correct test-first red
state — mirrors tests/unit/test_health.py's original design before
partgraph.util.health existed):

Imports: stdlib only, plus ``partgraph.util.container``
(``engine_command``/``compose_command``) and ``partgraph.util.health``
(``probe_health``). NEVER imports ``partgraph.cli`` or any embed/query/load
module (leaf discipline; mirrors container.py / health.py / index_health.py).
NOT re-exported from ``partgraph/util/__init__.py`` (ADR-0018 Section 4
precedent, set by index_health.py). Two ARCHITECTURE-level regressions this
file cannot mechanically enforce on itself (its own top-level import already
hard-fails collection until the module exists, so any test-level "skip if
absent" logic placed HERE would be unreachable dead code) live instead in
``tests/unit/test_lifecycle_architecture.py``, which imports nothing from
``partgraph.util.lifecycle`` at module level and therefore always collects:
the "no hard-coded docker/podman literal" static scan, the "never imports
partgraph.cli/embed/query/load" static scan (Gate 3b finding 3b-H1), and the
"partgraph.util does not re-export lifecycle's functions" check (3b-L2).

Module constants (frozen, named — never derived at runtime):
  - ``PARTGRAPH_CONTAINER_NAME: str`` = "partgraph-dgraph" — the S1 selector:
    the EXACT container name docker/docker-compose.yml declares.
  - ``PARTGRAPH_DATA_VOLUME: str`` = "partgraph_dgraph_data" — the S2
    selector: the named data volume declared in docker-compose.yml. Matched
    by EXACT string equality only — never ``.startswith()``/``.endswith()``
    (a live in-repo precedent, tests/integration/test_dgraph_lifecycle.py's
    OWN `.endswith("partgraph_dgraph_data")` mount check, exists for a
    DIFFERENT, legitimate reason there and must NOT be copied into this
    selector, where it would wrongly match e.g.
    ``partgraph_dgraph_data_backup`` — Gate 3a finding 3a-H4).
  - ``PARTGRAPH_UNIT_NAME: str`` = "partgraph-dgraph.service" — the quadlet
    unit name. A FROZEN CONSTANT: never built from any engine-returned string
    (Sec finding — a poisoned container name must never be able to influence
    which systemd unit gets targeted).
  - ``PARTGRAPH_WATCHED_PORTS: tuple[int, ...]`` = (8081, 9081, 8001) — the S3
    selector: PartGraph's own reserved host ports (docker/docker-compose.yml).
  - ``ENUMERATE_TIMEOUT_S``, ``INSPECT_TIMEOUT_S``, ``STOP_TIMEOUT_S``,
    ``SYSTEMCTL_TIMEOUT_S``: finite, named, bounded ``float`` timeouts for
    every subprocess.run call this module makes (mirrors
    HEALTH_PROBE_TIMEOUT_S / ADR-0007's bounded-constant precedent). NEVER
    ``None`` (unbounded).
  - ``STOP_GRACE_SECONDS: int`` — the engine's OWN ``-t`` grace-period value
    passed to ``stop -t <n> <id>`` (distinct from the Python-level subprocess
    ``timeout=`` kwarg above).
  - ``MAX_PS_OUTPUT_BYTES: int`` — a finite, named ceiling on the byte length
    of ``ps``'s stdout the parser will even ATTEMPT to decode (Gate 3a finding
    3a-M5). Extends the same bounded-constant discipline to untrusted engine
    OUTPUT, not just to timeouts: output at or beyond this bound is treated as
    malformed (degrades to an empty result, never raises, never attempts to
    ``json.loads`` an unbounded payload).

Frozen dataclasses:
  - ``Instance(id: str, name: str, image: str, status: str,
    ports: tuple[int, ...], owned_by: str, mounts_data_volume: bool)`` —
    ``owned_by`` is one of the literal strings ``"S1"``/``"S2"``/``"S3"``/
    ``"UNKNOWN"`` (the fourth tag added by Gate 5 finding A — see below).
    Only S1/S2/S3/UNKNOWN-classified containers are ever returned by
    :func:`find_partgraph_instances` — an unrelated container (e.g. every
    cve-graph container) is excluded entirely, never present in the returned
    tuple with some other tag. ``id`` is the engine-assigned, opaque
    container ID: it is the ONLY value :func:`stop_all` ever uses as an
    engine ``stop``/``container inspect`` TARGET (Gate 3a finding 3a-H1) —
    ``name`` is for DISPLAY only. This matters because S2 classifies by
    volume mount, independent of name: stopping by NAME would reopen a
    TOCTOU window between the survivor enumeration and the stop call (a
    different container could, in principle, come to answer to that name in
    between), whereas an engine-assigned ID cannot be reused by a different
    live container.
  - ``UnitState(present: bool, load_state: str | None,
    active_state: str | None, wanted_by_default: bool | None)`` —
    ``wanted_by_default`` is ``None`` when undeterminable (NEVER guessed).
  - ``DownResult(stopped: tuple[str, ...],
    skipped_foreign_port_holders: tuple[str, ...], unit_stopped: bool,
    survivors: tuple[str, ...], still_serving_health: bool,
    undetermined: tuple[str, ...])``. Every tuple here carries NAMES (never
    ids) — DownResult is the display-facing DTO. Unlike
    :class:`~partgraph.util.health.HealthResult` and
    :class:`~partgraph.util.index_health.IndexIntegrityResult`, DownResult
    deliberately carries NO ``message: str`` field (Gate 3b finding 3b-L1):
    every user-facing string `db down` prints (the A8 survivor line, the A9
    unowned-port advisory, the plain success line, and the Gate 5 finding A
    "could not verify" line below) is composed in cli.py from DownResult's
    structured fields, keeping ALL of `db down`'s user-facing text in ONE
    place rather than splitting it across the leaf and the CLI the way
    `db status`/`db check-index` do. ``undetermined`` (Gate 5 finding A) is
    the names of instances still classified ``"UNKNOWN"`` after the FINAL
    verification pass — a ``container inspect`` failure alone during the
    pre-stop sweep never populates it, since only verification decides the
    exit code (mirrors A12's phase-1 absorption: "do not over-fire").

Public functions (the ONLY public surface; everything else is private):
  - ``find_partgraph_instances(*, engine_prefix: list[str] | None = None,
    which=shutil.which, environ=None) -> tuple[Instance, ...]`` — READ-ONLY.
    Runs ``<prefix> ps --all --format json`` (never ``--filter``), bounded to
    :data:`MAX_PS_OUTPUT_BYTES`. For EVERY successfully-parsed row carrying
    both a non-empty ``Names`` list and an ``Id`` (a row missing either, an
    empty ``Names`` list, or a non-dict array element is SKIPPED — never
    crashes the whole enumeration, Gate 3a finding 3a-H3), runs ``<prefix>
    container inspect --format json <container-id>`` (by opaque ID — NEVER by
    name, so a foreign container's NAME never reaches an inspect argv) to
    determine :attr:`Instance.mounts_data_volume`, which is a TRI-STATE
    result internally (mounts / does-not-mount / COULD NOT DETERMINE — the
    inspect call itself failed: timeout, non-zero exit, or an unparseable
    payload). Classifies ownership by EXACT Python string comparison, in this
    PRIORITY order: (1) name == PARTGRAPH_CONTAINER_NAME -> S1; (2) mounts the
    named volume (PARTGRAPH_DATA_VOLUME, never a prefix/suffix/substring
    match) -> S2; (3) inspect COULD NOT DETERMINE the mount status -> "UNKNOWN"
    (Gate 5 finding A) — checked BEFORE the port test, regardless of whether
    the row also holds a watched port: an undetermined mount status is NEVER
    confidently downgraded to "just a port holder, safe to leave"; (4)
    positively does not mount the volume AND holds a PARTGRAPH_WATCHED_PORTS
    host port -> S3; (5) else excluded entirely (not PartGraph's, never
    returned). ``PARTGRAPH_WATCHED_PORTS`` host ports are extracted from
    EITHER shape a `ps --format json` ``Ports`` field is observed to take —
    podman's ``list[dict]`` (each entry carrying a ``host_port`` int) OR
    Docker's comma-joined string (e.g. ``"0.0.0.0:8081->8080/tcp"``, Gate 5
    finding B); either shape parses identically, and a malformed or empty
    value of EITHER shape degrades to no ports, never raises. A name failing a
    strict, POSITIVE allow-list charset check (the Docker/podman
    container-name grammar ``^[a-zA-Z0-9][a-zA-Z0-9_.-]*$``, Gate 3a finding
    3a-M7) is EXCLUDED before classification — it is never returned, and its
    raw string never reaches any subprocess argv. ``engine_prefix`` defaults
    to :func:`partgraph.util.container.engine_command`'s result when ``None``
    (resolved with the given ``which``/``environ``).
  - ``unit_state(*, which=shutil.which) -> UnitState`` — READ-ONLY. Runs
    ``systemctl --user show <PARTGRAPH_UNIT_NAME> --property=LoadState
    --property=ActiveState --property=SubState --property=UnitFileState
    --property=WantedBy`` and parses the ``Key=Value`` lines. Returns
    ``UnitState(present=False, ...)`` WITHOUT invoking subprocess at all when
    ``which("systemctl")`` is ``None``.
  - ``stop_all(*, engine_prefix=None, which=shutil.which, environ=None,
    compose_down: Callable[[], None], probe_health: Callable[[], Any] | None
    = None, dry_run: bool = False) -> DownResult`` — the full orchestrator.
    ``compose_down`` is REQUIRED, keyword-only, and carries NO default (Gate
    3b finding 3b-M1): a caller must decide EXPLICITLY whether/how compose is
    invoked rather than silently no-op-ing phase 2 — this forces every future
    caller (PR-B2's ``ensure_running()``, PR-C's ``should_stop_for_idle()``)
    to make that call explicitly rather than inheriting a permissive
    default. Order: (1) query :func:`unit_state`; if present and active, run
    ``systemctl --user stop <PARTGRAPH_UNIT_NAME>`` (skipped entirely under
    ``dry_run=True``; a FAILURE here — non-zero exit or a timeout — is
    ABSORBED: phases 2-4 still run, A12); (2) call the injected
    ``compose_down`` callback (skipped under ``dry_run=True``). Unlike phase
    1, an EXCEPTION raised by ``compose_down`` propagates OUT of
    :func:`stop_all` completely UNMODIFIED and short-circuits phases 3 and 4
    entirely (Gate 3b finding 3b-M2) — a sharp, deliberate asymmetry: a
    failed systemd-unit stop is survivable, a failed compose invocation is
    not; (3) call :func:`find_partgraph_instances` and, for every SURVIVING
    S1/S2 instance, run ``<prefix> stop -t <STOP_GRACE_SECONDS> <id>``
    (target is the instance's ``id``, never its ``name`` — skipped under
    ``dry_run=True``, enumeration/inspection still happens, nothing is
    stopped; an "UNKNOWN"-classified instance is NEVER a stop target here
    either, same as S3 — Gate 5 finding A); (4) call
    :func:`find_partgraph_instances` AGAIN (verification re-enumeration) to
    populate ``survivors`` (by NAME, for display) AND ``undetermined``: the
    names of every instance STILL classified "UNKNOWN" in THIS final pass
    (Gate 5 finding A) — an inspect failure confined to phase 3 alone never
    reaches ``undetermined``; only phase 4's verdict does.
    ``probe_health`` defaults to a lazy import of
    :func:`partgraph.util.health.probe_health` when ``None``; the injected
    seam is how `partgraph.cli`'s ALREADY module-level-imported
    ``probe_health`` (patched by CLI tests at ``partgraph.cli.probe_health``)
    flows through to this leaf without the leaf importing anything from
    ``partgraph.cli``.

This file mirrors the hermetic, injected-seam style of test_container.py
(fake ``which``) and test_health.py (fake HTTP seam / dataclass-contract
checks): no test in this file opens a real socket, starts a real container,
sleeps, or reads the real wall clock. Every subprocess outcome is injected via
a scripted, STATEFUL fake ``subprocess.run`` (patched at the
``subprocess.run`` call site, mirroring how cli.py's own ``_run_compose`` is
tested, and mirroring tests/unit/test_cli_db_down.py's stateful
``_make_scripted_run`` — a successful ``stop`` genuinely removes a container
from what the NEXT ``ps`` call reports, so "survived the stop" and "was
stopped" are distinguishable, not a static snapshot).
"""

from __future__ import annotations

import dataclasses
import inspect
import json
import math
import subprocess
from types import SimpleNamespace
from unittest.mock import patch

import pytest

# ---------------------------------------------------------------------------
# Lazy/eager import guard: this whole file is expected to ERROR at collection
# with ModuleNotFoundError until src/partgraph/util/lifecycle.py exists — the
# correct test-first red state (mirrors test_health.py before health.py
# existed).
# ---------------------------------------------------------------------------

from partgraph.util.lifecycle import (  # noqa: E402
    ENUMERATE_TIMEOUT_S,
    INSPECT_TIMEOUT_S,
    MAX_PS_OUTPUT_BYTES,
    PARTGRAPH_CONTAINER_NAME,
    PARTGRAPH_DATA_VOLUME,
    PARTGRAPH_UNIT_NAME,
    PARTGRAPH_WATCHED_PORTS,
    STOP_GRACE_SECONDS,
    STOP_TIMEOUT_S,
    SYSTEMCTL_TIMEOUT_S,
    DownResult,
    Instance,
    UnitState,
    find_partgraph_instances,
    stop_all,
    unit_state,
)

# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------


def _ps_row(container_id: str, name: str, image: str, *, state: str = "running",
            host_ports: tuple[int, ...] = ()) -> dict:
    """Build one canonical `<engine> ps --all --format json` row.

    A single, consistent per-row schema is used for BOTH the JSON-array and
    the NDJSON fixtures in this file: the LIVE-VERIFIED unknown is the OUTER
    envelope shape (array vs newline-delimited), not the per-row field names.
    """
    return {
        "Id": container_id,
        "Names": [name],
        "Image": image,
        "State": state,
        "Ports": [
            {
                "host_ip": "127.0.0.1",
                "host_port": p,
                "container_port": 8080,
                "protocol": "tcp",
            }
            for p in host_ports
        ],
    }


def _mounts(*volume_names: str, destination: str = "/dgraph") -> list[dict]:
    """Build a `container inspect --format json` `.Mounts` fixture."""
    return [
        {"Type": "volume", "Name": v, "Destination": destination}
        for v in volume_names
    ]


def _docker_ports_string(*host_ports: int, container_port: int = 8080,
                          protocol: str = "tcp", host_ip: str = "0.0.0.0") -> str:
    """Build a Docker-style comma-joined `Ports` string, e.g.
    "0.0.0.0:8081->8080/tcp, 0.0.0.0:9081->8080/tcp" — mirrors the EXACT
    shape `docker ps --format json` reports (Gate 5 finding B), distinct
    from podman's `list[dict]` shape `_ps_row` builds by default.
    """
    return ", ".join(f"{host_ip}:{p}->{container_port}/{protocol}" for p in host_ports)


def _ps_row_with_ports_field(container_id: str, name: str, image: str, *,
                              state: str = "running", ports_field: object) -> dict:
    """Like `_ps_row`, but with an EXPLICIT, already-shaped `Ports` value —
    a Docker-style string, a malformed string, or an empty string (Gate 5
    finding B; podman's `list[dict]` shape is already covered by `_ps_row`
    itself).
    """
    return {
        "Id": container_id,
        "Names": [name],
        "Image": image,
        "State": state,
        "Ports": ports_field,
    }


class _Proc:
    """Minimal stand-in for subprocess.CompletedProcess."""

    def __init__(self, *, stdout: str = "", stderr: str = "", returncode: int = 0) -> None:
        self.stdout = stdout
        self.stderr = stderr
        self.returncode = returncode


def _is_ps_call(argv: list[str]) -> bool:
    return "ps" in argv and "--all" in argv


def _is_inspect_call(argv: list[str]) -> bool:
    return "container" in argv and "inspect" in argv


def _is_engine_stop_call(argv: list[str]) -> bool:
    return bool(argv) and argv[0] != "systemctl" and "stop" in argv and "compose" not in argv


def _is_systemctl_show_call(argv: list[str]) -> bool:
    return bool(argv) and argv[0] == "systemctl" and "show" in argv


def _is_systemctl_stop_call(argv: list[str]) -> bool:
    return bool(argv) and argv[0] == "systemctl" and "stop" in argv and "show" not in argv


_UNIT_NOT_FOUND_LINES = [
    "LoadState=not-found", "ActiveState=", "SubState=", "UnitFileState=", "WantedBy=",
]


def _make_scripted_run(  # noqa: PLR0913 — one keyword-only knob per scriptable outcome.
    *,
    initial_rows: list[dict],
    mounts_by_id: dict[str, list[dict]] | None = None,
    unit_lines: list[str] | None = None,
    ps_stdout_override: str | None = None,
    stop_returncode: int = 0,
    stop_fails_ids: frozenset[str] = frozenset(),
    ps_raises_on_call_index: int | None = None,
    inspect_fails_ids_by_pass: dict[int, frozenset[str]] | None = None,
):
    """Return (fake_run, calls) — a STATEFUL subprocess.run stand-in.

    ``fake_run`` dispatches on argv shape (never trusts call ORDER). ``live``
    is the in-memory {container_id: row} set. A successful engine `stop`
    (target NOT in ``stop_fails_ids``) flips that row's ``State`` to
    ``"exited"`` — it is NEVER popped/removed from ``live``. `db down`'s
    locked verb surface is `stop`-only (never `rm`): a real engine still
    LISTS a stopped container under `ps --all` in state ``exited``; modelling
    a successful stop as full removal is `rm` semantics, a modelling error
    (this is the same category of bug GATE-PR7 A18 fixed — asserting a
    container must not EXIST rather than must not be RUNNING). So a SECOND
    `ps` call (a verification re-enumeration) STILL lists a stopped
    container — it just carries a NOT_RUNNING status now, exactly like a
    real engine — and STILL triggers a fresh `container inspect` call on it
    (the row is not gone), which is what makes "survived the stop" and "was
    stopped" genuinely distinguishable, mirroring
    tests/unit/test_cli_db_down.py's `_make_scripted_run` (Gate 3a finding
    3a-M6 / Gate 6 fixture-premise fix). ``ps_stdout_override`` lets a test
    replace the ps response body verbatim (empty string / malformed text /
    an oversized payload) for every ps call. ``calls`` records every (argv,
    kwargs) pair in order.

    ``inspect_fails_ids_by_pass`` (Gate 5 finding A) maps a 1-indexed `ps`
    PASS NUMBER (1 = the first `find_partgraph_instances()` call a test
    makes — e.g. `stop_all()`'s pre-stop sweep; 2 = a SECOND call — e.g.
    `stop_all()`'s verification re-enumeration) to the set of container ids
    whose `container inspect` call should FAIL (non-zero exit) during that
    specific pass, so "fails on both passes" vs "only during verification"
    vs "only during the pre-stop sweep" are all independently scriptable.
    """
    mounts_by_id = mounts_by_id or {}
    unit_lines = unit_lines if unit_lines is not None else _UNIT_NOT_FOUND_LINES
    inspect_fails_ids_by_pass = inspect_fails_ids_by_pass or {}
    live: dict[str, dict] = {row["Id"]: row for row in initial_rows}
    calls: list[tuple[list[str], dict]] = []
    ps_call_count = 0

    def _fake(argv, **kwargs):  # noqa: PLR0911 — one branch per scriptable verb.
        nonlocal ps_call_count
        calls.append((list(argv), dict(kwargs)))
        if _is_systemctl_show_call(argv):
            return _Proc(stdout="\n".join(unit_lines))
        if _is_systemctl_stop_call(argv):
            return _Proc(returncode=0)
        if _is_inspect_call(argv):
            cid = argv[-1]
            failing_ids = inspect_fails_ids_by_pass.get(ps_call_count, frozenset())
            if cid in failing_ids:
                return _Proc(returncode=1, stderr="inspect failed")
            return _Proc(stdout=json.dumps([{"Id": cid, "Mounts": mounts_by_id.get(cid, [])}]))
        if _is_ps_call(argv):
            ps_call_count += 1
            if ps_raises_on_call_index == ps_call_count:
                raise subprocess.TimeoutExpired(cmd=argv, timeout=10)
            if ps_stdout_override is not None:
                return _Proc(stdout=ps_stdout_override)
            return _Proc(stdout=json.dumps(list(live.values())))
        if _is_engine_stop_call(argv):
            target_id = argv[-1]
            if target_id in stop_fails_ids:
                return _Proc(returncode=1, stderr="stop failed")
            # `stop` is not `rm`: the row stays LISTED, now in a NOT_RUNNING
            # state, exactly like a real engine (`db down`'s verb surface is
            # stop-only). NEVER pop it — see the docstring above.
            if target_id in live:
                live[target_id] = {**live[target_id], "State": "exited"}
            return _Proc(returncode=stop_returncode)
        raise AssertionError(f"unscripted subprocess.run call in test fixture: {argv}")

    return _fake, calls


# ---------------------------------------------------------------------------
# CONTRACT — module constants
# ---------------------------------------------------------------------------


def test_partgraph_container_name_and_volume_constants_match_compose_file() -> None:
    """Given the compose file declares container_name and volume literals.
    When the module constants are read directly.
    Then they equal the exact values docker/docker-compose.yml declares.
    """
    assert PARTGRAPH_CONTAINER_NAME == "partgraph-dgraph"
    assert PARTGRAPH_DATA_VOLUME == "partgraph_dgraph_data"
    assert set(PARTGRAPH_WATCHED_PORTS) == {8081, 9081, 8001}


@pytest.mark.parametrize(
    "constant",
    [ENUMERATE_TIMEOUT_S, INSPECT_TIMEOUT_S, STOP_TIMEOUT_S, SYSTEMCTL_TIMEOUT_S],
)
def test_named_timeouts_are_finite_bounded_floats(constant: float) -> None:
    """Given every subprocess call this module makes carries a bounded timeout.
    When each named timeout constant is read directly.
    Then it is a finite float strictly greater than zero (never None/unbounded
    — mirrors HEALTH_PROBE_TIMEOUT_S / ADR-0007's bounded-constant precedent).
    """
    assert isinstance(constant, float)
    assert math.isfinite(constant)
    assert constant > 0


def test_stop_grace_seconds_is_a_positive_bounded_int() -> None:
    """Given STOP_GRACE_SECONDS is the engine's OWN `-t` grace period.
    When it is read directly.
    Then it is a positive int, distinct from the Python-level STOP_TIMEOUT_S
    subprocess watchdog (the watchdog must exceed the grace period, or the
    Python side would abort before the engine's own grace period elapses).
    """
    assert isinstance(STOP_GRACE_SECONDS, int)
    assert STOP_GRACE_SECONDS > 0
    assert STOP_TIMEOUT_S > STOP_GRACE_SECONDS


def test_max_ps_output_bytes_is_a_finite_positive_bound() -> None:
    """[3a-M5] Given MAX_PS_OUTPUT_BYTES bounds how much of `ps`'s stdout the
    parser will even attempt to decode.
    When the constant is read directly.
    Then it is a positive int (a genuine, finite ceiling — mirrors
    HEALTH_PROBE_TIMEOUT_S/INDEX_PROBE_TIMEOUT_S's bounded-constant
    discipline, extended here to untrusted engine OUTPUT rather than time).
    """
    assert isinstance(MAX_PS_OUTPUT_BYTES, int)
    assert MAX_PS_OUTPUT_BYTES > 0


# ---------------------------------------------------------------------------
# CONTRACT — dataclass shapes
# ---------------------------------------------------------------------------


def test_dataclasses_are_frozen_with_exact_contract_fields() -> None:
    """CONTRACT: Given Instance/UnitState/DownResult are the DTOs this module
    returns.
    When each is instantiated.
    Then each exposes EXACTLY its pinned field set and is frozen (a consumer
    cannot mutate a result after the fact — mirrors HealthResult).
    Instance's field set includes ``id`` (Gate 3a finding 3a-H1) alongside
    the display-only ``name``. DownResult's field set includes
    ``undetermined`` (Gate 5 finding A) alongside the existing ``survivors``.
    """
    instance = Instance(
        id="cid-abc123", name="partgraph-dgraph", image="dgraph/standalone:v25.3.4",
        status="running", ports=(8081,), owned_by="S1", mounts_data_volume=True,
    )
    assert {f.name for f in dataclasses.fields(instance)} == {
        "id", "name", "image", "status", "ports", "owned_by", "mounts_data_volume",
    }
    with pytest.raises(dataclasses.FrozenInstanceError):
        instance.owned_by = "S2"  # type: ignore[misc]

    unit = UnitState(present=True, load_state="loaded", active_state="active",
                      wanted_by_default=True)
    assert {f.name for f in dataclasses.fields(unit)} == {
        "present", "load_state", "active_state", "wanted_by_default",
    }
    with pytest.raises(dataclasses.FrozenInstanceError):
        unit.present = False  # type: ignore[misc]

    result = DownResult(
        stopped=(), skipped_foreign_port_holders=(), unit_stopped=False,
        survivors=(), still_serving_health=False, undetermined=(),
    )
    assert {f.name for f in dataclasses.fields(result)} == {
        "stopped", "skipped_foreign_port_holders", "unit_stopped",
        "survivors", "still_serving_health", "undetermined",
    }
    with pytest.raises(dataclasses.FrozenInstanceError):
        result.unit_stopped = True  # type: ignore[misc]


def test_unit_state_wanted_by_default_is_none_when_undeterminable() -> None:
    """CONTRACT: Given UnitState.wanted_by_default per contract must be
    ``None`` when undeterminable rather than guessed.
    When a UnitState is built with no WantedBy evidence.
    Then wanted_by_default is None (not True and not False).
    """
    unit = UnitState(present=False, load_state=None, active_state=None,
                      wanted_by_default=None)
    assert unit.wanted_by_default is None


# ---------------------------------------------------------------------------
# AC-P2 — ps output parsing: JSON array vs NDJSON must be identical
# ---------------------------------------------------------------------------


def test_parse_ps_json_array() -> None:
    """AC-P2: Given `<engine> ps --all --format json` answers with a single
    JSON ARRAY (podman's documented outer shape).
    When find_partgraph_instances() is called.
    Then the exact-name match is parsed into an S1 Instance with the right
    id/name/image/status/ports.
    """
    rows = [_ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4",
                     host_ports=(8081, 9081, 8001))]
    fake_run, _calls = _make_scripted_run(
        initial_rows=rows, mounts_by_id={"id-s1": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    inst = instances[0]
    assert inst.id == "id-s1"
    assert inst.name == "partgraph-dgraph"
    assert inst.image == "dgraph/standalone:v25.3.4"
    assert inst.status == "running"
    assert set(inst.ports) == {8081, 9081, 8001}
    assert inst.owned_by == "S1"


def test_parse_ps_ndjson() -> None:
    """AC-P2: Given the SAME single-container fixture as the JSON-array test,
    but `ps` answers with newline-delimited JSON (docker's outer shape)
    instead of a JSON array.
    When find_partgraph_instances() is called.
    Then the result is IDENTICAL to the JSON-array case — the parser accepts
    BOTH outer shapes and produces the same Instance.
    """
    row = _ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4",
                   host_ports=(8081, 9081, 8001))
    ndjson = json.dumps(row) + "\n"
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"id-s1": _mounts("partgraph_dgraph_data")},
        ps_stdout_override=ndjson,
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].id == "id-s1"
    assert instances[0].name == "partgraph-dgraph"
    assert instances[0].owned_by == "S1"


def test_parse_ps_empty_returns_empty() -> None:
    """AC-P2: Given `ps --all --format json` answers with an EMPTY string
    (zero containers on the host at all).
    When find_partgraph_instances() is called.
    Then it returns an empty tuple — never raises.
    """
    fake_run, _calls = _make_scripted_run(initial_rows=[], ps_stdout_override="")
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert instances == ()


def test_parse_ps_malformed_returns_empty() -> None:
    """AC-P2: Given `ps --all --format json` answers with garbage/non-JSON
    text (a corrupt engine response).
    When find_partgraph_instances() is called.
    Then it returns an empty tuple — never raises, never crashes `db down`.
    """
    fake_run, _calls = _make_scripted_run(
        initial_rows=[], ps_stdout_override="{not json at all]###"
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert instances == ()


def test_ps_output_exceeding_bound_treated_as_malformed() -> None:
    """[3a-M5] Given `ps`'s stdout is LARGER than MAX_PS_OUTPUT_BYTES bytes (a
    hostile/wedged engine flooding the response).
    When find_partgraph_instances() is called.
    Then the oversized payload is treated as malformed WITHOUT attempting to
    `json.loads` it — degrades to an empty tuple, never raises, never spends
    unbounded time/memory decoding an unbounded response (extends the
    existing timeout-bound discipline to output SIZE).
    """
    oversized = "[" + ("1234567890" * ((MAX_PS_OUTPUT_BYTES // 10) + 10)) + "]"
    assert len(oversized.encode("utf-8")) > MAX_PS_OUTPUT_BYTES
    fake_run, _calls = _make_scripted_run(initial_rows=[], ps_stdout_override=oversized)
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert instances == ()


# ---------------------------------------------------------------------------
# [3a-H3] Per-row malformed ps JSON — one bad row must never crash the whole
# enumeration, and other well-formed rows in the SAME batch must still be
# classified correctly (degrade to omission of the bad row, never to a global
# empty set or a crash).
# ---------------------------------------------------------------------------


def test_parse_ps_row_missing_names_excluded_not_crashed() -> None:
    """[3a-H3] Given a batch with one row missing the `Names` key entirely
    alongside one well-formed S1 row.
    When find_partgraph_instances() is called.
    Then the malformed row is silently skipped and the well-formed row is
    still classified correctly — no exception propagates.
    """
    good = _ps_row("id-good", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    bad = {"Id": "id-bad", "Image": "dgraph/standalone:v25.3.4", "State": "running", "Ports": []}
    stdout = json.dumps([bad, good])
    fake_run, _calls = _make_scripted_run(
        initial_rows=[], mounts_by_id={"id-good": []}, ps_stdout_override=stdout,
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name for i in instances}
    assert names == {PARTGRAPH_CONTAINER_NAME}, (
        f"a row missing 'Names' must be skipped, not crash the batch: {instances!r}"
    )


def test_parse_ps_row_empty_names_list_excluded_not_crashed() -> None:
    """[3a-H3] Given a batch with one row whose `Names` is an EMPTY list
    alongside one well-formed S1 row.
    When find_partgraph_instances() is called.
    Then the malformed row is silently skipped (no IndexError) and the
    well-formed row is still classified correctly.
    """
    good = _ps_row("id-good", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    bad = {"Id": "id-bad", "Names": [], "Image": "x", "State": "running", "Ports": []}
    stdout = json.dumps([bad, good])
    fake_run, _calls = _make_scripted_run(
        initial_rows=[], mounts_by_id={"id-good": []}, ps_stdout_override=stdout,
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name for i in instances}
    assert names == {PARTGRAPH_CONTAINER_NAME}, (
        f"a row with an empty 'Names' list must be skipped, not crash: {instances!r}"
    )


def test_parse_ps_row_non_dict_element_excluded_not_crashed() -> None:
    """[3a-H3] Given the ps JSON array contains a NON-DICT element (a bare
    string) alongside one well-formed S1 row.
    When find_partgraph_instances() is called.
    Then the non-dict element is silently skipped (no AttributeError from
    calling `.get()` on a string) and the well-formed row is still
    classified correctly.
    """
    good = _ps_row("id-good", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    stdout = json.dumps(["just-a-bare-string-not-a-row", good])
    fake_run, _calls = _make_scripted_run(
        initial_rows=[], mounts_by_id={"id-good": []}, ps_stdout_override=stdout,
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name for i in instances}
    assert names == {PARTGRAPH_CONTAINER_NAME}, (
        f"a non-dict array element must be skipped, not crash the batch: {instances!r}"
    )


def test_parse_ps_row_missing_id_excluded_not_crashed() -> None:
    """[3a-H3] Given a batch with one row missing the `Id` key entirely
    alongside one well-formed S1 row.
    When find_partgraph_instances() is called.
    Then the malformed row is silently skipped (it can never be inspected —
    there is no id to target `container inspect` with) and the well-formed
    row is still classified correctly.
    """
    good = _ps_row("id-good", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    bad = {"Names": ["nameless-id-row"], "Image": "x", "State": "running", "Ports": []}
    stdout = json.dumps([bad, good])
    fake_run, calls = _make_scripted_run(
        initial_rows=[], mounts_by_id={"id-good": []}, ps_stdout_override=stdout,
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name for i in instances}
    assert names == {PARTGRAPH_CONTAINER_NAME}, (
        f"a row missing 'Id' must be skipped, not crash the batch: {instances!r}"
    )
    for argv, _kwargs in calls:
        assert "nameless-id-row" not in argv


# ---------------------------------------------------------------------------
# [Gate 5 Finding B] Docker's `Ports` shape (a comma-joined string, e.g.
# "0.0.0.0:8081->8081/tcp") must parse IDENTICALLY to podman's `list[dict]`
# shape. `_row_ports` only handled the podman shape, so S3 silently never
# fired on a Docker engine — mirrors the dual-shape coverage already given to
# `Id`/`Names` above (Gate 3a finding 3a-H3-adjacent), now extended to
# `Ports`.
# ---------------------------------------------------------------------------


def test_docker_shaped_ports_string_single_mapping_matches_podman_list_shape() -> None:
    """Gate 5 Finding B: Given the EXACT Docker `ps --format json` shape —
    "0.0.0.0:8081->8080/tcp" — for a container matching neither S1 nor S2,
    and the SAME logical mapping expressed in podman's `list[dict]` shape.
    When find_partgraph_instances() is called on each independently.
    Then BOTH are classified S3 (holds a watched host port) identically.
    """
    docker_row = _ps_row_with_ports_field(
        "id-docker", "some-other-service", "nginx:1.27.3",
        ports_field=_docker_ports_string(8081),
    )
    podman_row = _ps_row("id-podman", "some-other-service", "nginx:1.27.3",
                          host_ports=(8081,))

    for row, cid in [(docker_row, "id-docker"), (podman_row, "id-podman")]:
        fake_run, _calls = _make_scripted_run(initial_rows=[row], mounts_by_id={cid: []})
        with patch("subprocess.run", side_effect=fake_run):
            instances = find_partgraph_instances(engine_prefix=["docker"])
        assert len(instances) == 1, f"{cid}: {instances!r}"
        assert instances[0].owned_by == "S3", f"{cid}: {instances!r}"
        assert set(instances[0].ports) == {8081}, f"{cid}: {instances!r}"


def test_docker_shaped_ports_string_multiple_comma_separated_mappings_parsed() -> None:
    """Gate 5 Finding B: Given a Docker-shaped `Ports` string with TWO
    comma-separated host-port mappings — "0.0.0.0:8081->8080/tcp,
    0.0.0.0:9081->9080/tcp".
    When find_partgraph_instances() is called.
    Then BOTH host ports (8081 and 9081) are extracted into Instance.ports,
    and the container is classified S3.
    """
    ports_string = ", ".join(["0.0.0.0:8081->8080/tcp", "0.0.0.0:9081->9080/tcp"])
    row = _ps_row_with_ports_field(
        "id-multi", "some-other-service", "nginx:1.27.3", ports_field=ports_string,
    )
    fake_run, _calls = _make_scripted_run(initial_rows=[row], mounts_by_id={"id-multi": []})
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert set(instances[0].ports) == {8081, 9081}
    assert instances[0].owned_by == "S3"


def test_docker_shaped_ports_string_malformed_degrades_to_no_ports() -> None:
    """Gate 5 Finding B: Given a `Ports` string matching neither engine's
    real shape (garbage text).
    When find_partgraph_instances() is called on a container matching
    neither S1 nor S2.
    Then it degrades to NO ports — excluded entirely, never crashes —
    mirrors the existing "malformed row degrades to omission" philosophy
    (Gate 3a finding 3a-H3).
    """
    row = _ps_row_with_ports_field(
        "id-malformed", "some-other-service", "nginx:1.27.3",
        ports_field="not-a-port-mapping-at-all",
    )
    fake_run, _calls = _make_scripted_run(initial_rows=[row], mounts_by_id={"id-malformed": []})
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert instances == (), (
        f"a malformed Ports string must degrade to no ports, not crash: {instances!r}"
    )


def test_docker_shaped_ports_string_empty_degrades_to_no_ports() -> None:
    """Gate 5 Finding B: Given an EMPTY `Ports` string (a real, common
    Docker shape for a container publishing no ports at all).
    When find_partgraph_instances() is called on a container matching
    neither S1 nor S2.
    Then it degrades to no ports, excluded entirely, never crashes.
    """
    row = _ps_row_with_ports_field(
        "id-empty-ports", "some-other-service", "nginx:1.27.3", ports_field="",
    )
    fake_run, _calls = _make_scripted_run(initial_rows=[row], mounts_by_id={"id-empty-ports": []})
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert instances == ()


def test_podman_list_shaped_ports_still_work_unchanged() -> None:
    """Gate 5 Finding B (regression pin): Given the ORIGINAL podman
    `list[dict]` `Ports` shape, unchanged, for a container matching
    neither S1 nor S2, holding a watched port.
    When find_partgraph_instances() is called.
    Then it is STILL classified S3 — the Docker-string fix must not break
    the podman shape that already worked.
    """
    row = _ps_row("id-podman-still-ok", "some-other-service", "nginx:1.27.3",
                   host_ports=(9081,))
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"id-podman-still-ok": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].owned_by == "S3"
    assert set(instances[0].ports) == {9081}


def test_docker_shaped_ports_on_s1_container_does_not_change_classification() -> None:
    """Gate 5 Finding B: Given a container named EXACTLY
    PARTGRAPH_CONTAINER_NAME (S1) that ALSO publishes a Docker-shaped
    `Ports` string.
    When find_partgraph_instances() is called.
    Then it is still classified S1 — ports never override name-based
    ownership, regardless of the `Ports` field's shape.
    """
    row = _ps_row_with_ports_field(
        "id-s1-docker-ports", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4",
        ports_field=_docker_ports_string(8081, 9081, 8001),
    )
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"id-s1-docker-ports": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].owned_by == "S1"
    assert set(instances[0].ports) == {8081, 9081, 8001}


def test_docker_shaped_ports_on_s2_container_does_not_change_classification() -> None:
    """Gate 5 Finding B: Given a container with an ARBITRARY name that
    mounts the PartGraph data volume (S2) and ALSO publishes a Docker-shaped
    `Ports` string.
    When find_partgraph_instances() is called.
    Then it is still classified S2 — ports never override volume-mount
    ownership, regardless of the `Ports` field's shape.
    """
    row = _ps_row_with_ports_field(
        "id-s2-docker-ports", "systemd-partgraph-dgraph-duplicate",
        "dgraph/standalone:v25.3.4", ports_field=_docker_ports_string(8081),
    )
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row],
        mounts_by_id={"id-s2-docker-ports": _mounts(PARTGRAPH_DATA_VOLUME)},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].owned_by == "S2"


# ---------------------------------------------------------------------------
# Selector policy (S1 / S2 / S3) — locked
# ---------------------------------------------------------------------------


def test_selects_exact_name_only() -> None:
    """Given one container named EXACTLY 'partgraph-dgraph' and a SECOND
    container named 'partgraph-dgraph-backup' (a substring/prefix collision,
    mounting nothing, holding no watched port).
    When find_partgraph_instances() is called.
    Then only the EXACT match is classified S1; the '-backup' container is
    excluded entirely — S1 is exact string equality, never a prefix/substring
    match.
    """
    rows = [
        _ps_row("id-exact", "partgraph-dgraph", "dgraph/standalone:v25.3.4"),
        _ps_row("id-backup", "partgraph-dgraph-backup", "dgraph/standalone:v25.3.4"),
    ]
    fake_run, _calls = _make_scripted_run(
        initial_rows=rows,
        mounts_by_id={"id-exact": [], "id-backup": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name: i.owned_by for i in instances}
    assert names.get("partgraph-dgraph") == "S1"
    assert "partgraph-dgraph-backup" not in names, (
        "A substring/prefix name match must NEVER be classified S1: "
        f"got instances={instances!r}"
    )


def test_leading_space_and_case_variation_are_not_s1() -> None:
    """[3a-L11] Given a container named ' partgraph-dgraph' (leading space)
    and a second named 'Partgraph-Dgraph' (case variation) — neither
    mounting the data volume nor holding a watched port.
    When find_partgraph_instances() is called.
    Then NEITHER is classified S1 (or anything else) — a defensive
    regression pin so a later "helpful" `.strip()`/`.casefold()`
    normalization can never silently reopen this collision.
    """
    row_space = _ps_row("id-space", " partgraph-dgraph", "dgraph/standalone:v25.3.4")
    row_case = _ps_row("id-case", "Partgraph-Dgraph", "dgraph/standalone:v25.3.4")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row_space, row_case],
        mounts_by_id={"id-space": [], "id-case": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name for i in instances}
    assert " partgraph-dgraph" not in names
    assert "Partgraph-Dgraph" not in names
    assert instances == (), (
        "A leading-space or case-varied name must never be classified S1 "
        f"(nor anything else here). Got: {instances!r}"
    )


def test_selects_by_data_volume_mount() -> None:
    """Given a container with an ARBITRARY name (e.g. the quadlet-generated
    duplicate) that mounts the named `partgraph_dgraph_data` volume at
    /dgraph, and does NOT hold any watched port.
    When find_partgraph_instances() is called.
    Then it is classified S2 with mounts_data_volume=True — ownership is
    volume-mount based, independent of name.
    """
    rows = [_ps_row("id-quadlet", "systemd-partgraph-dgraph", "dgraph/standalone:v25.3.4")]
    fake_run, _calls = _make_scripted_run(
        initial_rows=rows,
        mounts_by_id={"id-quadlet": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].id == "id-quadlet"
    assert instances[0].owned_by == "S2"
    assert instances[0].mounts_data_volume is True


def test_volume_name_substring_does_not_match_s2() -> None:
    """[3a-H4] Given three containers: one mounting
    'partgraph_dgraph_data_backup' (a SUFFIX collision), one mounting
    'not_partgraph_dgraph_data' (a PREFIX collision), and one mounting the
    EXACT 'partgraph_dgraph_data' — none named S1, none holding a watched
    port.

    tests/integration/test_dgraph_lifecycle.py:288-289 uses
    `name.endswith("partgraph_dgraph_data")` for its OWN legitimate reason —
    that is a live in-repo precedent a careless implementer of THIS selector
    could copy and still pass every other current unit test, which is why
    this collision is pinned explicitly here.

    When find_partgraph_instances() is called.
    Then the two substring-colliding containers are excluded entirely; only
    the exact-volume-name container is classified S2.
    """
    row_suffix = _ps_row("id-suffix-collision", "svc-a", "nginx:1.27.3")
    row_prefix = _ps_row("id-prefix-collision", "svc-b", "nginx:1.27.3")
    row_exact = _ps_row("id-exact-volume", "svc-c", "dgraph/standalone:v25.3.4")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row_suffix, row_prefix, row_exact],
        mounts_by_id={
            "id-suffix-collision": _mounts("partgraph_dgraph_data_backup"),
            "id-prefix-collision": _mounts("not_partgraph_dgraph_data"),
            "id-exact-volume": _mounts(PARTGRAPH_DATA_VOLUME),
        },
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    names = {i.name: i.owned_by for i in instances}
    assert "svc-a" not in names, "a volume-name SUFFIX collision must not match S2"
    assert "svc-b" not in names, "a volume-name PREFIX collision must not match S2"
    assert names.get("svc-c") == "S2"


def test_port_holder_is_report_only() -> None:
    """Given a container with an ARBITRARY name, no PartGraph volume mount,
    holding host port 8081 (one of PARTGRAPH_WATCHED_PORTS).
    When find_partgraph_instances() is called AND stop_all() runs end-to-end
    on this fixture (nothing else present).
    Then the enumeration classifies it S3, AND stop_all() records it under
    ``skipped_foreign_port_holders`` — it is NEVER passed to an engine `stop`
    call (report-only, never stopped).
    """
    rows = [_ps_row("id-foreign", "some-other-service", "nginx:1.27.3",
                     host_ports=(8081,))]
    fake_run, calls = _make_scripted_run(
        initial_rows=rows, mounts_by_id={"id-foreign": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
        assert instances[0].owned_by == "S3"

        result = stop_all(
            engine_prefix=["docker"],
            compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    assert "some-other-service" in result.skipped_foreign_port_holders
    assert result.stopped == ()
    for argv, _kwargs in calls:
        assert not _is_engine_stop_call(argv), (
            f"An S3 (report-only) port holder must NEVER be `stop`-ped: {argv}"
        )


def test_cve_graph_fixture_selects_nothing() -> None:
    """A6 (HIGHEST PRIORITY NEGATIVE): Given the REAL observed host state
    (names/images only — live-verified this session) — zero PartGraph
    containers and exactly these five dgraph-family/unrelated containers, on
    host ports distinct from PARTGRAPH_WATCHED_PORTS (illustrative test
    values; the live session did not record their exact port numbers):
    min-web (nginx:1.27.3), cve-ratel (dgraph/ratel:latest),
    cve-zero (dgraph/dgraph:v24.0.0), cve-alpha (dgraph/dgraph:v24.0.0),
    cve-loader (localhost/cve-loader:latest).
    When find_partgraph_instances() is called.
    Then it returns an EMPTY tuple — none of the five match S1 (name), S2
    (volume) or S3 (watched port); image family (`dgraph/*`) is NOT a
    selector.
    """
    rows = [
        _ps_row("cid-minweb", "min-web", "nginx:1.27.3", host_ports=(18080,)),
        _ps_row("cid-ratel", "cve-ratel", "dgraph/ratel:latest", host_ports=(18000,)),
        _ps_row("cid-zero", "cve-zero", "dgraph/dgraph:v24.0.0", host_ports=(15080,)),
        _ps_row("cid-alpha", "cve-alpha", "dgraph/dgraph:v24.0.0", host_ports=(18081, 19081)),
        _ps_row("cid-loader", "cve-loader", "localhost/cve-loader:latest"),
    ]
    mounts_by_id = {
        "cid-minweb": [],
        "cid-ratel": [],
        "cid-zero": _mounts("cve-graph_dgraph_zero", destination="/dgraph"),
        "cid-alpha": _mounts("cve-graph_dgraph_alpha", destination="/dgraph"),
        "cid-loader": [],
    }
    fake_run, calls = _make_scripted_run(initial_rows=rows, mounts_by_id=mounts_by_id)

    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert instances == (), (
        f"cve-graph fixture must select NOTHING; got: {instances!r}"
    )
    forbidden_names = {"min-web", "cve-ratel", "cve-zero", "cve-alpha", "cve-loader"}
    forbidden_volumes = {"cve-graph_dgraph_zero", "cve-graph_dgraph_alpha"}
    for argv, _kwargs in calls:
        argv_text = " ".join(argv)
        for forbidden in forbidden_names | forbidden_volumes | {"systemd-cve-graph"}:
            assert forbidden not in argv_text, (
                f"cve-graph identifier {forbidden!r} leaked into engine argv: {argv}"
            )
        assert not _is_engine_stop_call(argv)


def test_hostile_name_rejected() -> None:
    """A14: Given `ps` returns a container whose name starts with '-' (a
    flag-injection attempt) and ALSO mounts partgraph_dgraph_data (it would
    otherwise be a legitimate S2 match).
    When find_partgraph_instances() is called.
    Then the hostile-named row is EXCLUDED entirely (never returned as an
    Instance) and its raw string never reaches any subprocess argv anywhere.
    """
    hostile = "-rf ; rm -rf / #"
    rows = [_ps_row("id-hostile", hostile, "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        initial_rows=rows, mounts_by_id={"id-hostile": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert instances == (), (
        f"A hostile container name must never be classified/returned: {instances!r}"
    )
    for argv, _kwargs in calls:
        for token in argv:
            assert hostile not in token, (
                f"Hostile name leaked into subprocess argv: {argv}"
            )


@pytest.mark.parametrize(
    "hostile_name",
    ["-flag-like", "has space", "semi;colon", "dollar$sign", "quote'mark"],
)
def test_hostile_name_rejected_parametrized_charsets(hostile_name: str) -> None:
    """A14: Given a variety of hostile name shapes (leading '-', whitespace,
    ';', '$', quote).
    When find_partgraph_instances() is called on a fixture where that name
    mounts the data volume.
    Then every one is excluded and never reaches a subprocess argv.
    """
    rows = [_ps_row("id-x", hostile_name, "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        initial_rows=rows, mounts_by_id={"id-x": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert instances == ()
    for argv, _kwargs in calls:
        for token in argv:
            assert hostile_name not in token


# ---------------------------------------------------------------------------
# [3a-M7] Positive allow-list: the Docker/podman container-name grammar
# ``^[a-zA-Z0-9][a-zA-Z0-9_.-]*$``. A DENY-list of enumerated hostile
# characters (above) can never be exhaustive; the module's actual contract
# is a POSITIVE allow-list, pinned directly here.
# ---------------------------------------------------------------------------


def test_allowlist_positive_normal_docker_style_name_is_accepted() -> None:
    """[3a-M7] Given a container mounting the data volume under a NORMAL,
    docker/podman-grammar-valid name (letters, digits, '_', '.', '-').
    When find_partgraph_instances() is called.
    Then it is NOT rejected — it is classified S2 as expected. Proves the
    allow-list is a genuine ALLOW-list (accepts valid names), not merely a
    deny-list of a few enumerated characters in disguise.
    """
    row = _ps_row("id-ok", "my_service-01.local", "dgraph/standalone:v25.3.4")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"id-ok": _mounts(PARTGRAPH_DATA_VOLUME)},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])
    assert len(instances) == 1
    assert instances[0].name == "my_service-01.local"
    assert instances[0].owned_by == "S2"


@pytest.mark.parametrize(
    "hostile_name",
    [
        pytest.param("bad\nname", id="embedded-newline"),
        pytest.param("bad`name", id="backtick"),
        pytest.param("bad|name", id="pipe"),
        pytest.param("a" * 300, id="excessively-long"),
        pytest.param("has[bracket]name", id="brackets"),
    ],
)
def test_allowlist_negative_table_rejects_hostile_shapes(hostile_name: str) -> None:
    """[3a-M7] Given the positive allow-list grammar
    ``^[a-zA-Z0-9][a-zA-Z0-9_.-]*$``.
    When find_partgraph_instances() is called on a fixture where a container
    otherwise mounting the data volume (an S2 match) carries a name
    violating that grammar (embedded newline, backtick, pipe, or an
    excessively long 300-char name).
    Then it is excluded entirely and never reaches any subprocess argv.

    [Gate 3b item 12 / 3a-M8]: the "brackets" case doubles as the
    Rich-`markup=False` regression the amendment asked for — a `[`/`]`
    -bearing name is rejected HERE, at the allow-list, before it could ever
    reach a Rich-rendered CLI display string, so a dedicated CLI-level
    `markup=False` test would be redundant with this stronger, earlier
    guarantee and is intentionally NOT added separately.
    """
    row = _ps_row("id-hostile", hostile_name, "dgraph/standalone:v25.3.4")
    fake_run, calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"id-hostile": _mounts(PARTGRAPH_DATA_VOLUME)},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert instances == ()
    for argv, _kwargs in calls:
        for token in argv:
            assert hostile_name not in token


# ---------------------------------------------------------------------------
# AC-P3 — engine-neutral argv (no --filter/--ignore authority, no Go-template
# field names, only verbs/flags documented for BOTH engines)
# ---------------------------------------------------------------------------


def test_no_docker_only_or_podman_only_flags() -> None:
    """AC-P3: Given a fixture requiring a ps call + at least one inspect call.
    When find_partgraph_instances() runs.
    Then NO argv anywhere uses `--filter` or `--ignore` as ownership
    authority, and no argv references a Go-template field (`{{.` anywhere).
    """
    rows = [_ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        initial_rows=rows, mounts_by_id={"id-s1": _mounts("partgraph_dgraph_data")},
    )
    with patch("subprocess.run", side_effect=fake_run):
        find_partgraph_instances(engine_prefix=["docker"])

    assert calls, "fixture produced no subprocess.run calls to inspect"
    for argv, _kwargs in calls:
        for token in argv:
            assert token != "--filter", f"--filter used as authority: {argv}"
            assert token != "--ignore", f"--ignore used: {argv}"
            assert "{{." not in token, f"Go-template field name relied upon: {argv}"


def test_engine_prefix_comes_from_engine_command() -> None:
    """AC-P1: Given engine_prefix is NOT explicitly supplied.
    When find_partgraph_instances() is called.
    Then it resolves the argv prefix via
    partgraph.util.container.engine_command() (patched here as a spy) —
    never a hard-coded 'docker'/'podman' literal.
    """
    fake_run, calls = _make_scripted_run(initial_rows=[], ps_stdout_override="[]")
    with (
        patch("partgraph.util.lifecycle.engine_command", return_value=["podman"]) as mock_engine,
        patch("subprocess.run", side_effect=fake_run),
    ):
        find_partgraph_instances()

    assert mock_engine.called, (
        "find_partgraph_instances() must resolve its engine prefix via "
        "engine_command() when engine_prefix is not supplied."
    )
    assert calls, "no subprocess.run call was made"
    assert calls[0][0][0] == "podman", (
        f"argv prefix must be engine_command()'s return value; got {calls[0][0]!r}"
    )


def test_all_calls_have_bounded_timeout() -> None:
    """A15: Given a fixture that triggers a ps call AND an inspect call.
    When find_partgraph_instances() runs.
    Then EVERY subprocess.run call carries a finite, positive `timeout=`
    kwarg — never an unbounded/absent timeout (a hung engine must never hang
    `db down`).
    """
    rows = [_ps_row("id-s1", "partgraph-dgraph", "dgraph/standalone:v25.3.4")]
    fake_run, calls = _make_scripted_run(
        initial_rows=rows, mounts_by_id={"id-s1": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        find_partgraph_instances(engine_prefix=["docker"])

    assert calls
    for argv, kwargs in calls:
        timeout = kwargs.get("timeout")
        assert timeout is not None, f"call missing timeout=: {argv}"
        assert isinstance(timeout, int | float)
        assert math.isfinite(timeout)
        assert timeout > 0


# ---------------------------------------------------------------------------
# unit_state() — systemd quadlet unit introspection
# ---------------------------------------------------------------------------


def test_unit_state_parses_loaded_active() -> None:
    """A3: Given `systemctl --user show ...` answers with the LIVE-VERIFIED
    shape for a loaded, active unit wanted by default.target.
    When unit_state() is called.
    Then UnitState.present is True, load_state='loaded',
    active_state='active', wanted_by_default is True.
    """
    fake_run, calls = _make_scripted_run(
        initial_rows=[],
        unit_lines=[
            "LoadState=loaded",
            "ActiveState=active",
            "SubState=running",
            "UnitFileState=generated",
            "WantedBy=default.target",
        ],
    )
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        result = unit_state()

    assert result.present is True
    assert result.load_state == "loaded"
    assert result.active_state == "active"
    assert result.wanted_by_default is True
    assert len(calls) == 1
    assert _is_systemctl_show_call(calls[0][0])


def test_unit_state_parses_not_found() -> None:
    """A11: Given `systemctl --user show ...` answers LoadState=not-found (no
    such unit was ever generated on this host).
    When unit_state() is called.
    Then UnitState.present is False.
    """
    fake_run, _calls = _make_scripted_run(
        initial_rows=[],
        unit_lines=["LoadState=not-found", "ActiveState=inactive",
                    "SubState=dead", "UnitFileState=", "WantedBy="],
    )
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        result = unit_state()

    assert result.present is False


def test_unit_state_parses_failed() -> None:
    """Given `systemctl --user show ...` reports a loaded unit whose
    ActiveState is 'failed' (a crashed prior run).
    When unit_state() is called.
    Then UnitState.present is True and active_state == 'failed' — a failed
    unit is still 'present', distinct from not-found.
    """
    fake_run, _calls = _make_scripted_run(
        initial_rows=[],
        unit_lines=["LoadState=loaded", "ActiveState=failed",
                    "SubState=failed", "UnitFileState=generated",
                    "WantedBy=default.target"],
    )
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        result = unit_state()

    assert result.present is True
    assert result.active_state == "failed"


def test_unit_name_is_frozen_constant() -> None:
    """A3: Given PARTGRAPH_UNIT_NAME is a frozen module constant.
    When unit_state() builds its systemctl argv.
    Then the constant equals 'partgraph-dgraph.service' exactly, AND the
    argv passed to systemctl contains that exact constant string — never a
    name derived from ps/engine output.
    """
    assert PARTGRAPH_UNIT_NAME == "partgraph-dgraph.service"

    fake_run, calls = _make_scripted_run(initial_rows=[])
    with patch("subprocess.run", side_effect=fake_run), patch("shutil.which", return_value="/usr/bin/systemctl"):
        unit_state()

    assert calls
    assert PARTGRAPH_UNIT_NAME in calls[0][0]


def test_systemctl_argv_has_user_never_system_never_sudo() -> None:
    """A3: Given BOTH unit_state()'s read (show) call and stop_all()'s write
    (stop) call.
    When each systemctl invocation is inspected.
    Then every one contains '--user' and NEITHER 'sudo' as argv[0] NOR
    '--system' anywhere.
    """
    fake_run, calls = _make_scripted_run(
        initial_rows=[],
        unit_lines=["LoadState=loaded", "ActiveState=active",
                    "SubState=running", "UnitFileState=generated",
                    "WantedBy=default.target"],
    )
    with (
        patch("subprocess.run", side_effect=fake_run),
        patch("shutil.which", return_value="/usr/bin/systemctl"),
    ):
        unit_state()
        stop_all(
            engine_prefix=["docker"],
            compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    systemctl_calls = [argv for argv, _kwargs in calls if argv and argv[0] == "systemctl"]
    assert systemctl_calls, "no systemctl call was recorded"
    for argv in systemctl_calls:
        assert argv[0] != "sudo"
        assert "sudo" not in argv
        assert "--user" in argv
        assert "--system" not in argv


# ---------------------------------------------------------------------------
# AC-P4 — PARTGRAPH_CONTAINER_ENGINE routes through detection identically
# ---------------------------------------------------------------------------


def test_partgraph_container_engine_env_var_routes_through_detection() -> None:
    """AC-P4: Given PARTGRAPH_CONTAINER_ENGINE=docker is set in the injected
    environ mapping.
    When find_partgraph_instances() resolves its own engine prefix (no
    explicit engine_prefix override).
    Then engine_command() is called with that SAME environ — the override
    routes through the shared detection helper identically to how
    compose_command()/`db up`/`db down` already honour it.
    """
    fake_run, _calls = _make_scripted_run(initial_rows=[], ps_stdout_override="[]")
    with (
        patch(
            "partgraph.util.lifecycle.engine_command", return_value=["docker"]
        ) as mock_engine,
        patch("subprocess.run", side_effect=fake_run),
    ):
        find_partgraph_instances(environ={"PARTGRAPH_CONTAINER_ENGINE": "docker"})

    assert mock_engine.called
    _args, kwargs = mock_engine.call_args
    assert kwargs.get("environ") == {"PARTGRAPH_CONTAINER_ENGINE": "docker"}


# ---------------------------------------------------------------------------
# [3a-H1] stop_all() targets a container's opaque ID, never its name.
# ---------------------------------------------------------------------------


def test_stop_all_targets_container_id_never_name_in_stop_argv() -> None:
    """[3a-H1] Given a surviving S1 instance.
    When stop_all() issues its engine `stop` sweep.
    Then the LAST argv element (the stop TARGET) is the container's opaque
    id — never its name. S2 in particular classifies by volume mount,
    independent of name, so stopping by name would reopen a TOCTOU window
    between enumeration and stop; an engine-assigned id cannot be reused by
    a different live container. The NAME still surfaces in DownResult's
    display-facing `stopped` tuple.
    """
    row = _ps_row("cid-abc123", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    fake_run, calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"cid-abc123": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        result = stop_all(
            engine_prefix=["docker"], compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    stop_calls = [argv for argv, _k in calls if _is_engine_stop_call(argv)]
    assert stop_calls, "expected at least one engine stop call"
    for argv in stop_calls:
        assert argv[-1] == "cid-abc123", (
            f"stop target must be the container ID, never the name: {argv}"
        )
        assert PARTGRAPH_CONTAINER_NAME not in argv, (
            f"the container NAME must never appear in a stop argv: {argv}"
        )
    assert PARTGRAPH_CONTAINER_NAME in result.stopped, (
        "the NAME must still surface in DownResult.stopped for human display"
    )


def test_stop_all_survivor_and_verification_end_to_end() -> None:
    """[3a-M6] Given two S1/S2 survivors after compose down: one whose
    engine `stop` call SUCCEEDS (removed from the live set) and one whose
    `stop` call FAILS (returncode != 0, remains live).
    When stop_all() runs its full sweep + verification re-enumeration.
    Then DownResult.stopped contains only the NAME that was actually
    removed, and DownResult.survivors contains only the NAME that is still
    live after verification — proving the stateful fixture (and, once
    implemented, stop_all() itself) distinguishes "survived the stop" from
    "was stopped" rather than returning a static snapshot.
    """
    row_ok = _ps_row("cid-ok", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    row_stuck = _ps_row(
        "cid-stuck", "systemd-partgraph-dgraph-duplicate", "dgraph/standalone:v25.3.4"
    )
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row_ok, row_stuck],
        mounts_by_id={"cid-ok": [], "cid-stuck": _mounts(PARTGRAPH_DATA_VOLUME)},
        stop_fails_ids=frozenset({"cid-stuck"}),
    )
    with patch("subprocess.run", side_effect=fake_run):
        result = stop_all(
            engine_prefix=["docker"], compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    assert PARTGRAPH_CONTAINER_NAME in result.stopped
    assert "systemd-partgraph-dgraph-duplicate" not in result.stopped
    assert "systemd-partgraph-dgraph-duplicate" in result.survivors
    assert PARTGRAPH_CONTAINER_NAME not in result.survivors


# ---------------------------------------------------------------------------
# [Gate 5 Finding A] An `inspect` failure must never silently manufacture a
# clean result. `Instance.owned_by` gains a FOURTH tag, "UNKNOWN", for a row
# that is not S1 (name mismatch) and whose volume-mount status could not be
# determined (the `container inspect` call failed) — checked BEFORE the port
# test, so an undetermined mount status is NEVER confidently downgraded to
# "just a port holder, safe to leave" (mirrors the existing NOT_RUNNING
# deny-list philosophy: degrade toward suspicion, never toward a silent
# all-clear). "UNKNOWN" instances are NEVER stopped (same as S3), but
# DownResult gains `undetermined: tuple[str, ...]` — names of instances still
# classified UNKNOWN in the FINAL verification pass ONLY (an inspect failure
# confined to the pre-stop sweep alone is NOT fatal — "do not over-fire",
# mirrors A12's phase-1 absorption).
# ---------------------------------------------------------------------------


def test_inspect_failure_on_non_s1_row_yields_unknown_not_silent_exclusion() -> None:
    """Gate 5 Finding A: Given a container whose name does NOT match S1 and
    holds no watched port, whose `container inspect` call FAILS (non-zero
    exit).
    When find_partgraph_instances() is called.
    Then the row is NOT silently excluded — it is returned with
    owned_by == "UNKNOWN", never silently dropped as if unrelated.
    """
    row = _ps_row("id-maybe", "maybe-partgraph-duplicate", "dgraph/standalone:v25.3.4")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row],
        inspect_fails_ids_by_pass={1: frozenset({"id-maybe"})},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1, (
        f"an inspect failure must not silently exclude the row: {instances!r}"
    )
    assert instances[0].id == "id-maybe"
    assert instances[0].owned_by == "UNKNOWN"


def test_inspect_failure_on_row_holding_watched_port_still_unknown_not_s3() -> None:
    """Gate 5 Finding A: Given a container that ALSO holds a watched port
    (8081) but whose `inspect` call fails.
    When find_partgraph_instances() is called.
    Then it is classified UNKNOWN, NOT S3 — an undetermined volume-mount
    status must never be confidently downgraded to "just a port holder,
    safe to leave"; S3 is reserved for containers POSITIVELY confirmed not
    to mount our volume.
    """
    row = _ps_row("id-maybe-port", "maybe-partgraph-duplicate", "dgraph/standalone:v25.3.4",
                   host_ports=(8081,))
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row],
        inspect_fails_ids_by_pass={1: frozenset({"id-maybe-port"})},
    )
    with patch("subprocess.run", side_effect=fake_run):
        instances = find_partgraph_instances(engine_prefix=["docker"])

    assert len(instances) == 1
    assert instances[0].owned_by == "UNKNOWN"


def test_stop_all_inspect_fails_both_passes_s2_only_container_marks_undetermined() -> None:
    """Gate 5 Finding A: Given a container that WOULD classify S2 if inspect
    succeeded (an "S2-only-named" duplicate — not S1 by name, no watched
    port), but its `container inspect` call FAILS on BOTH the pre-stop
    sweep AND the verification pass.
    When stop_all() runs.
    Then DownResult.undetermined contains its name — `db down` must NEVER
    report clean success (empty survivors) while a possibly-still-running
    PartGraph instance's ownership could not be verified.
    """
    row = _ps_row("cid-maybe", "systemd-partgraph-dgraph-maybe", "dgraph/standalone:v25.3.4")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row],
        inspect_fails_ids_by_pass={1: frozenset({"cid-maybe"}), 2: frozenset({"cid-maybe"})},
    )
    with patch("subprocess.run", side_effect=fake_run):
        result = stop_all(
            engine_prefix=["docker"], compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    assert result.undetermined == ("systemd-partgraph-dgraph-maybe",), (
        f"an inspect failure on both passes must mark the container "
        f"undetermined, never silently clean: {result!r}"
    )
    assert result.stopped == (), (
        "an UNKNOWN instance (owned_by not in S1/S2) is never a stop "
        f"target — nothing was ever attempted: {result!r}"
    )
    assert result.survivors == ()


def test_stop_all_inspect_fails_only_during_verification_marks_undetermined() -> None:
    """Gate 5 Finding A: Given the SAME S2-only-named container, but inspect
    SUCCEEDS during the pre-stop sweep (correctly classified S2, so a
    `stop` IS attempted and SUCCEEDS) yet FAILS again during the
    verification pass (a transient re-failure). `db down`'s verb surface
    is `stop`-only, never `rm` (ADR-0021): a real engine still LISTS a
    stopped container under `ps --all` — it does not vanish — so the
    verification pass genuinely re-enumerates and re-inspects this exact
    row, and THAT inspect call is the one that fails.
    When stop_all() runs.
    Then the container's name is in BOTH `DownResult.stopped` (a `stop`
    call WAS issued and the engine reported success — that fact is real
    and does not become false just because we later could not re-confirm
    it) AND `DownResult.undetermined` (verification could not re-confirm
    its ownership, so `db down` still refuses to claim a clean result).
    This dual membership is deliberately accepted here, not weakened away:
    it is the honest report of "we acted, then lost the ability to
    verify" — pinned explicitly per the Gate 5/6 review exchange, and
    independently verified by the implementer against the (unchanged)
    production contract.
    """
    row = _ps_row("cid-maybe", "systemd-partgraph-dgraph-maybe", "dgraph/standalone:v25.3.4")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row],
        mounts_by_id={"cid-maybe": _mounts(PARTGRAPH_DATA_VOLUME)},
        inspect_fails_ids_by_pass={2: frozenset({"cid-maybe"})},
    )
    with patch("subprocess.run", side_effect=fake_run):
        result = stop_all(
            engine_prefix=["docker"], compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    assert result.undetermined == ("systemd-partgraph-dgraph-maybe",), (
        f"a verification-pass-only inspect failure must still withhold a "
        f"clean result: {result!r}"
    )
    assert result.stopped == ("systemd-partgraph-dgraph-maybe",), (
        "the earlier, successfully-issued stop is still an honest fact — "
        f"it must not be retracted just because re-verification failed: {result!r}"
    )
    assert result.survivors == ()


def test_stop_all_inspect_fails_only_during_pre_stop_sweep_is_not_fatal() -> None:
    """Gate 5 Finding A (the required asymmetry — "do not over-fire"): Given
    inspect FAILS during the pre-stop sweep for a container that, in
    truth, does NOT mount the PartGraph volume (a transient failure only —
    it resolves cleanly on retry), but SUCCEEDS during the verification
    pass and reveals it mounts nothing of ours.
    When stop_all() runs.
    Then DownResult.undetermined is EMPTY, nothing was ever attempted
    (`stopped` is also EMPTY: the row was never classified S1/S2 while
    inspect was failing, so it was never a stop target), and survivors is
    EMPTY — a pre-stop-sweep-only inspect failure, on its own, is NOT
    fatal: only the verification pass decides the exit code (mirrors
    A12's phase-1 absorption).
    """
    row = _ps_row("cid-unrelated", "totally-unrelated-service", "nginx:1.27.3")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row],
        mounts_by_id={"cid-unrelated": []},
        inspect_fails_ids_by_pass={1: frozenset({"cid-unrelated"})},
    )
    with patch("subprocess.run", side_effect=fake_run):
        result = stop_all(
            engine_prefix=["docker"], compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    assert result.undetermined == (), (
        "a pre-stop-sweep-only inspect failure must not, by itself, mark "
        f"anything undetermined once verification succeeds: {result!r}"
    )
    assert result.stopped == ()
    assert result.survivors == ()


def test_stop_all_inspect_succeeds_everywhere_undetermined_stays_empty() -> None:
    """Gate 5 Finding A (the happy path must stay clean): Given a normal S1
    survivor and inspect succeeding on every call (including the SECOND
    inspect the verification pass issues on this same, now-`exited`,
    row — `stop` is not `rm`; the row stays listed).
    When stop_all() runs its full sweep + verification.
    Then DownResult.undetermined is EMPTY and `stopped` contains EXACTLY
    the one instance that was stopped and verified gone — adding this new
    field must never make an already-clean run noisier.
    """
    row = _ps_row("cid-1", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    fake_run, _calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"cid-1": []},
    )
    with patch("subprocess.run", side_effect=fake_run):
        result = stop_all(
            engine_prefix=["docker"], compose_down=lambda: None,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )

    assert result.undetermined == ()
    assert result.survivors == ()
    assert result.stopped == (PARTGRAPH_CONTAINER_NAME,)


# ---------------------------------------------------------------------------
# [3b-M1 / 3b-M2] compose_down is required, keyword-only, no default; its
# exceptions propagate unmodified and short-circuit phases 3 and 4.
# ---------------------------------------------------------------------------


def test_compose_down_is_required_keyword_only_with_no_default() -> None:
    """[3b-M1] Given stop_all()'s `compose_down` parameter.
    When the signature is inspected.
    Then it is KEYWORD_ONLY and carries NO default
    (inspect.Parameter.empty) — a caller MUST decide explicitly whether/how
    to invoke compose, rather than silently no-op-ing phase 2. This forces
    PR-B2's ensure_running() and PR-C's should_stop_for_idle() to decide
    explicitly rather than inheriting a permissive default.
    """
    sig = inspect.signature(stop_all)
    param = sig.parameters["compose_down"]
    assert param.kind is inspect.Parameter.KEYWORD_ONLY
    assert param.default is inspect.Parameter.empty


class _ComposeDownFailure(RuntimeError):
    """A RuntimeError subclass standing in for a real compose-down failure.

    Deliberately NOT ``typer.Exit`` (whose own ``__mro__`` also includes
    ``RuntimeError``, which is exactly why cli.py's real `_run_compose`
    failure path will reach stop_all() this way) — a plain,
    Typer-independent exception keeps this leaf-level test fully decoupled
    from partgraph.cli/Typer.
    """


def test_compose_down_exception_propagates_unmodified_short_circuits_phases_3_and_4() -> None:
    """[3b-M2] Given the injected `compose_down` callback raises a
    RuntimeError subclass (modelling a real compose failure).
    When stop_all() runs (on a fixture with a survivor that WOULD otherwise
    need an engine-level stop).
    Then the exception propagates OUT of stop_all() completely UNMODIFIED
    (same instance), and NEITHER the engine stop sweep (phase 3) NOR the
    verification re-enumeration (phase 4) ever run — a sharp asymmetry
    versus phase 1 (a failed systemd unit stop is ABSORBED, A12): a failed
    compose_down is NOT survivable, by design.
    """
    row = _ps_row("cid-1", PARTGRAPH_CONTAINER_NAME, "dgraph/standalone:v25.3.4")
    fake_run, calls = _make_scripted_run(
        initial_rows=[row], mounts_by_id={"cid-1": []},
    )
    boom = _ComposeDownFailure("compose down failed")

    def _compose_down_raises() -> None:
        raise boom

    with (
        patch("subprocess.run", side_effect=fake_run),
        pytest.raises(_ComposeDownFailure) as excinfo,
    ):
        stop_all(
            engine_prefix=["docker"], compose_down=_compose_down_raises,
            probe_health=lambda: SimpleNamespace(healthy=False),
        )
    assert excinfo.value is boom

    assert not any(_is_engine_stop_call(argv) for argv, _k in calls), (
        "phase 3 (engine stop sweep) must never run after compose_down raises"
    )
    assert not any(_is_ps_call(argv) for argv, _k in calls), (
        "phase 4 (verification re-enumeration), and the phase-3 survivor "
        "enumeration it depends on, must never run after compose_down raises"
    )
